googlemock/CMakeLists.txt

Pretty trivial miss from the merging of the two tree.
Thanks.

googlemock: change guess of googletest's relative location from ../gtest to ../googletest

---

googletest/xcode/gtest.xcodeproj/project.pbxproj

Project file contained the 'README' instead of 'README.md' that's why the build failed with the fact that it can't copy this file for its proper location.
Signed-off-by: Gergő Nagy <gergo@getcodie.com>

xcode: project file corrected

---

googletest/docs/Primer.md

The markdown interpreter don't interpret the table otherwise.

FIX add missing blank line between text and table

---

googlemock/test/gmock-generated-actions_test.cc
googlemock/test/gmock-more-actions_test.cc

Googlemock has some tuples containing lvalue refs in its unit tests. These tuples are created with make_tuple, which is given temporaries. The make_tuple is in a function argument list.
A possibly overzealous static_assert in libc++'s std::tuple ctor
is firing in our 'Perform(make_tuple("hi"))' calls, so
we can't use its make_tuple here. Instead we will use
explicitly-constructed tuples constructed from non-temporary strings.
Workaround for llvm bug:
https://llvm.org/bugs/show_bug.cgi?id=20855
An alternative to https://github.com/google/googletest/pull/580 .

gmock unit tests: avoid make_tuple for lvalueref tuples.

---

googletest/Makefile.am

When trying to use the googletest in another project I found that there are some files missing in pkginclude. As a result, "make check" inside unpacked distribution fails. With this fix, it passes.

Adding missing header files to the distribution.

---

googlemock/Makefile.am

make dist followed by unzip and make fails without these files present in the distribution.
make distcheck, likewise, fails.
With this fix thing seem to work again.

Adding missing files to googlemock distribution.

---

googlemock/include/gmock/gmock-actions.h
googlemock/test/gmock-actions_test.cc
googlemock/test/gmock-matchers_test.cc
googletest/include/gtest/internal/gtest-port.h

This guards use of <type_traits> and its features with
GTEST_HAS_STD_TYPE_TRAITS_, and std::function with
GTEST_HAS_STD_FUNCTION_.

googlemock: Support C++11 language with pre-C++11 library

---

googlemock/test/gmock-matchers_test.cc

https://github.com/google/googletest/issues/610

googlemock: Disable WhenDynamicCastToTest tests when RTTI is off

---

googlemock/test/gmock-matchers_test.cc
googletest/test/gtest-port_test.cc

This fixes these warnings:
…\gtest\googletest\test\gtest-port_test.cc(78) : error C2220: warning treated as error - no 'object' file generated
…\gtest\googletest\test\gtest-port_test.cc(78) : warning C4309: 'static_cast' : truncation of constant value
…\gtest\googletest\test\gtest-port_test.cc(79) : warning C4309: 'static_cast' : truncation of constant value
…\gtest\googlemock\test\gmock-matchers_test.cc(2712) : error C2220: warning treated as error - no 'object' file generated
…\gtest\googlemock\test\gmock-matchers_test.cc(2706) : while compiling class template member function 'testing::gmock_matchers_test::FloatingPointTest<float>::FloatingPointTest(void)'
…\gtest\googlemock\test\gmock-matchers_test.cc(2896) : see reference to function template instantiation …

Fix warnings encountered in MSVC build of gtest/gmock tests

---

.travis.yml

Existing Travis configuration installs clang 3.0, which seems not being able to locate gcc 4.9.
Using white-listed clang 3.7 package instead.

Fix C++11 clang builds in Travis CI

---

CMakeLists.txt

Adding functionality to build googletest from the root directory

Adding CMakeLists.txt to the root dir

---

googletest/CMakeLists.txt

This is useful when GoogleTest is pulled in as an `ExternalProject` in a CMake superbuild.

Add CMake install rules for gtest libraries and headers

---

googlemock/docs/CheatSheet.md
googlemock/docs/CookBook.md
googlemock/docs/DevGuide.md
googlemock/docs/Documentation.md
googlemock/docs/ForDummies.md
googlemock/docs/FrequentlyAskedQuestions.md

Hi I did repair the links in the documentation.
I tried to use relative links wherever possible so that it will work on other servers.

fixed link in googlemock documentation

---

googlemock/CMakeLists.txt

Install rules where missing in the GMock CMakeLists.txt file. The result was that, when building GMock using CMake, the library was not being installed in the system.

Added missing CMake install rules for GMock

---

googlemock/CMakeLists.txt
googletest/CMakeLists.txt

I've verified on OS X 10.10.5 that with this change, googletest and googlemock builds with the following CMake versions:
- 2.6.4
- 2.8.10.2
- 2.8.11.1
- 3.4.1
I've also verified that the include directories are successfully attached to the targets when using CMake 2.8.11.1 and 3.4.1, and are not attached when using CMake 2.6.4 or 2.8.10.2, hence confirming the expected behaviour.

Add include dirs to targets if CMake version supports it

---

googletest/include/gtest/internal/gtest-port.h

As repository moved to github. All urls need to be changed. There is
still plenty to do.

Update GTEST_PROJECT_URL_ in internal/gtest-port.h

---

README.md

On google code, the main documentation pages were the "Google Test Primer" content. Currently it's hard to find that content on github, so add a direct link in the main README.md.

Add link to Google Test Primer docs in README.md

---

googlemock/src/gmock-spec-builders.cc
googlemock/test/gmock-spec-builders_test.cc
googlemock/test/gmock_output_test_golden.txt

Fix for #714
Note that there a number of other references to old docs, but according to #569 these will be fixed up in a bigger pass, so I didn't touch them.

Fix link that's returned when running tests. #714

---

googlemock/docs/ForDummies.md
googlemock/docs/v1_5/ForDummies.md
googlemock/docs/v1_6/ForDummies.md
googlemock/docs/v1_7/ForDummies.md
googletest/README.md
googletest/docs/AdvancedGuide.md
googletest/docs/FAQ.md
googletest/docs/V1_5_AdvancedGuide.md
googletest/docs/V1_6_AdvancedGuide.md
googletest/docs/V1_6_FAQ.md
googletest/docs/V1_7_AdvancedGuide.md
googletest/docs/V1_7_FAQ.md

Put occurrences of "#include" in a code span so they are not interpreted
as headers.
Other documents were not broken because the #include was not at the
start of the line, but put them in code spans anyway just in case the
text gets refilled in the future.

Fix formatting in AdvancedGuide.md

---

googletest/include/gtest/internal/gtest-port.h
googletest/src/gtest-port.cc
googletest/src/gtest.cc
googletest/test/gtest_env_var_test.py

If $XML_OUTPUT_FILE is set, and $GTEST_OUTPUT and --gtest_output are not
specified, produce output as if GTEST_OUTPUT=xml:$XML_OUTPUT_FILE had
been set.

Read Bazel's $XML_OUTPUT_FILE environment variable

---

appveyor.yml
googletest/cmake/internal_utils.cmake
googletest/test/gtest_list_tests_unittest.py
travis.sh

Run tests on appveyor https://ci.appveyor.com/project/KindDragon/googletest

Run MSVC tests on AppVeyor

---

googlemock/test/gmock-matchers_test.cc

I've seen the fix somewhere a couple of weeks ago, and I failed to find the source again. I'm actually not the author of this PR, someone else has already provided the exactly same solution somewhere.
Anyway, this PR fixes the issue #775 somehow.

Fixed issue #775. Mark the ConvertibleFromAny constructor as explicit, and fix operator overload issue for Unprintable

---

googletest/cmake/internal_utils.cmake
googletest/include/gtest/internal/gtest-port.h
googletest/test/gtest-port_test.cc
googletest/test/gtest_unittest.cc

Fixes #708.
Allows to compile googletest with MinGW when pthreads support is disabled.
Also, the cmake build automatically disables pthreads supportwhen MinGW is used.
Tested on Win7, with MinGW 4.8.1, cmake 3.5.0. All tests pass, except for gmock-matchers_test that fails because of a limitation of MinGW not being able to handle "too many sections", most likely unrelated to the issue being addressed here (see below).
Unfortunately, I am not able to (legally) test with MSVC compiler, anybody please help test.
Also tested on Linux, although I expect no differences.
cmake command line used for testing:
`cmake -G "MinGW Makefiles" -Dgtest_build_samples=ON -Dgmock_build_samples=ON -Dgtest_build_tests=ON -Dgmock_build_tests=ON ..`
MinGW "too many section" issue:
``` …
```

Fix compilation of googletest with MinGW using Win32 threads

---

googletest/include/gtest/internal/gtest-port.h
googletest/test/gtest-port_test.cc

@BillyDonahue PR #721 break build with Mingw-w64, this PR should fix this

Fix Mingw-w64 build

---

googletest/include/gtest/internal/gtest-port.h

This was not in Gingerbread for anything but ARM (even though the
libs were hacked to lie about it being available in gingerbread).

Fix detection of GTEST_HAS_CLONE for Android.

---

googlemock/README.md
googletest/README.md

Added content to the gtest and gmock build instructions with links to an
article explaining how to download googletest sources at CMake time
and then use `add_subdirectory()` to incorporate it directly into an
existing build. The preference for using CMake was made clearer in
the gmock readme and the advantage of building gtest and gmock
directly as part of an existing CMake build has been highlighted.

Added docs for ExternalProject download during CMake step

---

googlemock/README.md

This pull request offers a solution to issue #873, and ensures that every relative link in [googletest/googlemock/README.md](https://github.com/google/googletest/blob/master/googlemock/README.md) is working properly. It is likely that there are similar relative link issues in other parts of the documentation, which I will review.

Fixing broken relative links in Google Mock documentation

---

googletest/include/gtest/gtest-typed-test.h

If REGISTER_TYPED_TEST_CASE_P is included in a header file, but
the .cc file does not declare INSTANTIATE_TYPED_TEST_CASE_P, an
unused-variable warning may be raised by the compiler.
fixes #981

Add GTEST_ATTRIBUTE_UNUSED_ to REGISTER_TYPED_TEST_CASE_P

---

googletest/include/gtest/internal/gtest-port.h
googletest/test/gtest-printers_test.cc
googletest/test/gtest_catch_exceptions_test_.cc

Should fix #1033 
Fixes the following errors:
```
hash_map(17): error C2338: <hash_map> is deprecated and will be REMOVED. Please use <unordered_map>. You can define _SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS to acknowledge that you have received this warning. [googlemock\gtest\gtest-printers_test.vcxproj]
hash_set(17): error C2338: <hash_set> is deprecated and will be REMOVED. Please use <unordered_set>. You can define _SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS to acknowledge that you have received this warning. [googlemock\gtest\gtest-printers_test.vcxproj]
googletest\test\gtest_catch_exceptions_test_.cc(152): error C2220: warning treated as error - no 'object' file generated
googletest\test\gtest_catch_exceptions_test_.cc(152): warning C4297: …
```

Minimal changes to fix build failures on Microsoft Visual Studio 2015

---

googletest/include/gtest/internal/gtest-port.h
googletest/src/gtest.cc

I'm not sure if the `__MINGW_PRINTF_FORMAT` mess is necessary. We have it in BoringSSL's version of this macro to appease some Android build warning. I've included it here since I see some evidence GTest supports MinGW, but it may be more general than is necessary.
googletest doesn't currently build with clang's very aggressive `-Wformat-nonliteral` warning. It requires that all non-literal format strings come from the argument of a function annotated with a compatible format attribute.
Fixing that reports that `ColoredPrintf`'s callers weren't passing the normal `-Wformat` warning. Some messages were passed directly into the format string rather than via `"%s"`.

Annotate ColoredPrintf with the format attribute and fix bugs.

---

googletest/include/gtest/internal/custom/gtest-port.h
googletest/include/gtest/internal/gtest-port.h

This makes it possible for a port to define the specifier used for exported symbols without having to change Google Test.
Background: I'm trying to roll Google Test from 1.7.0 to 1.8.0 (or above) into Chromium and I'm running into a crasher in the ThreadLocal destructor for a static variable defined in Google Mock with the GTEST_API_ specifier. Some details are at https://bugs.chromium.org/p/chromium/issues/detail?id=630705#c28 and I can supply more, if it helps.
I realize this PR is not addressing the root cause of the crashes, but being able to replace the GTEST_API_ definition lets me make forward progress, and I can imagine that being able to define GTEST_API_ would come in handy for other projects as well. Will you please consider merging this?

Pick up GTEST_API_ definition in gtest/internal/custom/gtest-port.h.

---

.gitignore
googletest/xcode/gtest.xcodeproj/project.pbxproj

It looks like a few headers were added that did not get configured in the Xcode framework target fully. This results in program build-time errors. Reproduce the issue by:
1. Open googletest/xcode/gtest.xcodeproj in Xcode
2. Select the sample1_unittest-framework target
3. Choose Product/Run menu

Add missing headers to Xcode framework target.

---

googletest/include/gtest/gtest.h

This upstreams a Google-internal change.

Fixing typo in documentation.

---

googlemock/include/gmock/gmock-matchers.h
googlemock/include/gmock/gmock-spec-builders.h
googlemock/include/gmock/internal/gmock-internal-utils.h
googlemock/src/gmock-cardinalities.cc
googlemock/src/gmock-internal-utils.cc
googlemock/src/gmock-matchers.cc
googlemock/src/gmock-spec-builders.cc
googlemock/test/gmock-generated-actions_test.cc
googlemock/test/gmock-generated-function-mockers_test.cc
googlemock/test/gmock-generated-matchers_test.cc
googlemock/test/gmock-internal-utils_test.cc
googlemock/test/gmock-matchers_test.cc
googlemock/test/gmock-more-actions_test.cc
googlemock/test/gmock-nice-strict_test.cc
googlemock/test/gmock-spec-builders_test.cc
googlemock/test/gmock_stress_test.cc
googletest/include/gtest/gtest-printers.h
googletest/include/gtest/gtest-spi.h
googletest/include/gtest/internal/gtest-internal.h
googletest/include/gtest/internal/gtest-param-util.h
googletest/src/gtest-death-test.cc
googletest/src/gtest-internal-inl.h
googletest/src/gtest-port.cc
googletest/src/gtest.cc
googletest/test/gtest-death-test_test.cc
googletest/test/gtest-printers_test.cc
googletest/test/gtest_unittest.cc

This merges a Google-internal change (117235625).
Original CL description:
This CL was created manually in about an hour with sed, a Python script
to find all the places unqualified 'string' was mentioned, and some help
from Emacs to add the "std::" qualifications, plus a few manual tweaks.

Use std::string and ::string explicitly in gtest and gmock code.

---

googletest/include/gtest/gtest-printers.h

This upstreams a Google-internal change.
Original CL description:
The C++ standard says that function pointers are not implicitly
convertible to object pointers. Visual Studio disregards that and allows
implicit conversion between function pointers and object points, and
enough code relies on this that clang follows suit in
Microsoft-compatibility mode.
However, clang emits a -Wmicrosoft-cast warning when such a conversion
is done:
E:\b\c\b\win_clang\src\sandbox\win\src\sync_dispatcher.cc(42,7):
warning: implicit conversion between pointer-to-function and
pointer-to-object is a Microsoft extension [-Wmicrosoft-cast]
This change fixes this warning in gtest, while hopefully not changing
any behavior. The change does two things:
1. It replaces the if in DefaultPrintTo with SFINAE
2. In C++11 …

Fix -Wmicrosoft-cast warnings when using gtest with clang on Windows.

---

googletest/docs/AdvancedGuide.md

Updating the link with a valid one. The old one was considered obsolete by the publisher.

Fixing float comparison broken link

---

googletest/include/gtest/internal/gtest-port-arch.h
googletest/include/gtest/internal/gtest-port.h

NetBSD is a modern UNIX-like Operating System.
Enable GTEST_HAS_PTHREAD and GTEST_HAS_DEATH_TEST on NetBSD.

Add NetBSD support

---

googlemock/configure.ac

Fixed typo: `environmont` => `environment`.

Fixed typo

---

googletest/src/gtest.cc

Help says "FILE_PATH defaults to test_details.xml", but the real path is test_detail.xml.

Fix a typo

---

googlemock/docs/CookBook.md

The old language might mislead someone into thinking that the access level on the base class itself was changed. This happened to a co-worker of mine, a (relative) novice in C++.

Clarifying documentation language

---

googletest/src/gtest.cc

The rest of the (covered) codebase is already integer overflow clean.
This is a cherry-pick of an internal change.
TESTED=gtest_shuffle_test goes from fail to pass with -fsanitize=integer

Use wider types to prevent unsigned overflow diagnostics

---

googlemock/test/gmock-generated-actions_test.cc

This commit correct some typos in one of the lines - a wrong identifier and awkward phrasing. Please merge it as soon as possible. It is the resubmission of https://github.com/google/googletest/pull/978 .

Correct some typos in a comment

---

googletest/docs/V1_7_Primer.md

table "Basic Assertions" is now rendered correctly as table

Fix: Markdown in V1_7_Primer.md

---

googletest/docs/Primer.md

There are contradictory definitions of the term "test case", so prepare
new users in Primer.md to avoid confusion.
This pull request is related to issue #1085.

add note about different definitions of Test Case

---

googletest/src/gtest.cc

Re-use existing background color for Widows' console window.
Before fix:
After fix:
This fixes a problem where the background color for ColoredPrintf would be BLACK even if the user's console is using a different BG color.

Fix background color in ColoredPrintf

---

googlemock/docs/ForDummies.md

Add a hyphen to 'ad hoc' and change 'distance' to plural.

Fix a few documentation nits in the mock dummies guide

---

CMakeLists.txt
googlemock/CMakeLists.txt
googletest/CMakeLists.txt

Modify library install destinations to install .dll's to the correct location (`bin`, not `lib`), and to install other artifacts to the correct platform-dependent location by honoring `LIB_SUFFIX`. This is required for some distributions (e.g. Fedora) and will fix an issue that otherwise requires those distributions to patch the upstream sources.
Fixes #1161.

 Fix library install destinations

---

googlemock/docs/CookBook.md

SeArrayArgument => SetArrayArgument

Fix small typo in Cookbook: SeArrayArgument

---

README.md

Minor change to the README indicating [gtest-runner](https://github.com/nholthaus/gtest-runner), a Qt5 based UI and test-runner, as a related open-source project.

Documentation change to add related open source project

---

googletest/docs/AdvancedGuide.md

As explained on the previous link, the article has been rewritten and moved.

Fix the link to the float comparison article

---

README.md

> There is
> also an IRC channel on [OFTC](https://webchat.oftc.net/) (irc.oftc.net) #gtest available.
BTW, maybe switch to https://gitter.im/. It's easier too use for new users

Add links to IRC channel and Google Group

---

googletest/include/gtest/internal/gtest-port.h

fix for #886 null detection can be enabled on Solaris Studio starting from 12u4

enable null detection on Solaris Studio 12u4+

---

googlemock/CMakeLists.txt
googlemock/cmake/gmock.pc.in
googlemock/cmake/gmock_main.pc.in
googletest/CMakeLists.txt
googletest/cmake/gtest.pc.in
googletest/cmake/gtest_main.pc.in
googletest/cmake/internal_utils.cmake
googletest/docs/FAQ.md
googletest/docs/Pkgconfig.md

This PR adds support for pkgconfig. Pkgconfig is the quasi-standard for determining the required flags and libraries to link to. The `gtest-config` utility is not tractable, does not generalise, is not supported natively by any build system and is ultimately rather cumbersome. Autoconf/CMake/Waf/Scons/Meson all have methods to use pkg-config files, which is the proper build system agnostic way to determine the required flags.

Add support for pkgconfig

---

CMakeLists.txt

Fix a bug deciding whether to enable the option to install Google Test caused by one of the dependent option dependencies not being defined yet.
Fixes #1198; impossible to install Google Test if Google Mock is built.

Fix problem installing gtest when gmock enabled

---

googletest/CMakeLists.txt

This policy setting will silence a warning when using with a visibility settings on targets. Due to the forced `cmake_minimum_version`, policy settings in CMakeLists calling this one (including the main CMakeLists) are lost, forcing the change to be made here.

Adding CMake visibility policy setting

---

googlemock/msvc/2010/gmock.sln
googlemock/msvc/2010/gmock.vcxproj
googlemock/msvc/2010/gmock_config.props
googlemock/msvc/2010/gmock_main.vcxproj
googlemock/msvc/2010/gmock_test.vcxproj
googletest/msvc/2010/gtest-md.sln
googletest/msvc/2010/gtest-md.vcxproj
googletest/msvc/2010/gtest-md.vcxproj.filters
googletest/msvc/2010/gtest.sln
googletest/msvc/2010/gtest.vcxproj
googletest/msvc/2010/gtest.vcxproj.filters
googletest/msvc/2010/gtest_main-md.vcxproj
googletest/msvc/2010/gtest_main-md.vcxproj.filters
googletest/msvc/2010/gtest_main.vcxproj
googletest/msvc/2010/gtest_main.vcxproj.filters
googletest/msvc/2010/gtest_prod_test-md.vcxproj
googletest/msvc/2010/gtest_prod_test-md.vcxproj.filters
googletest/msvc/2010/gtest_prod_test.vcxproj
googletest/msvc/2010/gtest_prod_test.vcxproj.filters
googletest/msvc/2010/gtest_unittest-md.vcxproj
googletest/msvc/2010/gtest_unittest-md.vcxproj.filters
googletest/msvc/2010/gtest_unittest.vcxproj
googletest/msvc/2010/gtest_unittest.vcxproj.filters

VS2010 solution only to simplify old users (who used these solutions) upgrading to new gtest/gmock, new users should use CMake generated solutions. VS2010 solution can be opened in any new VS.

Support x64 configuration for VS2010 projects

---

googletest/docs/FAQ.md

There are two comments wrong in an example in Google Test's FAQ, which is fixed by this PR.

fix example's comment

---

googlemock/README.md
googlemock/docs/DevGuide.md
googlemock/include/gmock/gmock-generated-actions.h
googlemock/include/gmock/gmock-generated-actions.h.pump
googlemock/include/gmock/gmock-generated-matchers.h
googlemock/include/gmock/gmock-generated-matchers.h.pump
googlemock/scripts/fuse_gmock_files.py
googletest/docs/PumpManual.md
googletest/scripts/fuse_gtest_files.py
googletest/src/gtest.cc

change links from former code.google.com to current github repository

---

appveyor.yml

Tests disabled for mingw64
AppVeyor should pass after merging PR #856

AppVeyor MinGW-w64 test build

---

googletest/test/gtest-param-test_test.cc
googletest/test/gtest_unittest.cc

Non-primitive iterators should use prefix increments instead of postfix increments.

Performance fixes reported by cppcheck

---

googlemock/CMakeLists.txt
googletest/cmake/internal_utils.cmake

If the user's cmakelists.txt first look for threads using
find_package(Threads), then set(gtest_disable_pthreads ON),
and then include googletest. GoogleTest will not look for
threads. But since they have already been found before in
user's cmakelists, it will use them regardless.
This helped me fix build issue in https://github.com/darktable-org/rawspeed/commit/e079559f9e05597183f681cd94cff42b9c51a9d7
on windows/MSYS2, even though there are threads, and they
are usable, googletest build was failing with issues
about AutoHandle. I was first looking for threads, and only
then including googletest, so no matter the value of
gtest_disable_pthreads, it failed.
The other obvious solution is for user to first include
googletest, and only then look for threads by himself.
-----
Thoughts? …

CMake: use threads if allowed and found, not just if found.

---

travis.sh

Build on Travis CI can be speed up by running parallelized builds as suggested in [Travis Doc](https://docs.travis-ci.com/user/speeding-up-the-build/#Makefile-optimization).
Instead of setting an environment variable in `.travis.yml` as suggested by Travis, I propose to use the more flexible change in the shell script `travis.sh` which we have anyway.

run parallelized builds on Travis CI

---

.travis.yml

Travis-CI supports [caching](https://docs.travis-ci.com/user/caching) of different build artefacts.
Using `ccache` speeds up builds especially in case of minor changes (doc etc.).
The first build for this pull request does not show any acceleration, as the cache needs to be filled first. But further builds can be faster in case the cache contains fitting objects.

enable Travis ccache to speed up CI builds

---

.travis.yml
googletest/cmake/internal_utils.cmake
googletest/test/gtest-param-test_test.cc
googletest/test/gtest_unittest.cc

Using Release mode turns on the compiler's optimization which allows the compiler to discover more problems and omit some more warnings.
This enhances the coverage of hidden problems in comparison to running debug mode builds only.

switch one Trevis build to Release mode

---

.travis.yml

The valgrind package is not used in the current `travis.sh` build, so there is no need to install it on the build slaves.
... and remove explicit gcc installation (will be installed automatically as dependency of g++).

drop unused valgrind package from Travis build slave installation

---

.travis.yml

The environment variables SHARED_LIB, STATIC_LIB and CMAKE_PKG are currently not used neither in travis.sh nor by cmake.
Therefore they should be removed to avoid confusion and keep .travis.yml maintainable.
This is a followup to #1252 after resolving merge conflicts.

remove unused variables from travis environment

---

googletest/CMakeLists.txt

The link_directories() command not necessary, as the target_link_libraries command contains an absolute path already, and the path given doesn't exist anymore, leading only to linker warnings like:
```
ld: warning: directory not found for option '-L/Users/travis/build/google/googletest/build/googlemock/gtest/src'
```

remove obsolete link_directories command

---

googletest/src/gtest.cc
googletest/test/gtest_output_test_golden_lin.txt
googletest/test/gtest_unittest.cc
googletest/test/gtest_xml_output_unittest.py

instead of reading more like reversing the former "expected" and "actual"
roles of the LHS and RHS arguments.
This patch is manually applied from internal version (125109873)

Make the failure messages from EXPECT_EQ and friends actually symmetric (reopen of #1101)

---

googletest/CMakeLists.txt

Enable generating different library name to be compatible with CMake's `FindGTest`.

Add explicit `CMAKE_DEBUG_POSTFIX` option

---

googletest/include/gtest/internal/gtest-port.h

TempDir() function is declared twice, once in `internal/gtest-port.h`
and a second time in `gtest.h`.
Removes a warning with GCC when -Wredundant-decls is given.
Fixes issue ##1264.

Remove redundant declaration

---

googletest/include/gtest/gtest-param-test.h
googletest/include/gtest/gtest-param-test.h.pump
googletest/test/gtest-param-test_test.cc

Reverts google/googletest#1245, merged too early

Revert "Allow macros inside of parametrized test names."

---

googletest/include/gtest/gtest-printers.h

When compiling with [Objective-C ARC](https://clang.llvm.org/docs/AutomaticReferenceCounting.html), casting `id` (Objective-C object type) to `char*` is not allowed. However, casting to `void*` is possible. 
Casting the print value to `void*` first enables using GMock in Objective-C++ projects using ARC. For example, using `MOCK_METHOD` for a method that takes an Objective-C block as one of the parameters is now possible.

Make TypeWithoutFormatter compatible with Objective-C++ with ARC.

---

googlemock/docs/CookBook.md
googlemock/docs/FrequentlyAskedQuestions.md
googlemock/include/gmock/gmock-spec-builders.h
googlemock/src/gmock-internal-utils.cc
googlemock/src/gmock-spec-builders.cc
googlemock/test/gmock-cardinalities_test.cc
googlemock/test/gmock-internal-utils_test.cc
googlemock/test/gmock-spec-builders_test.cc
googletest/docs/AdvancedGuide.md
googletest/docs/FAQ.md
googletest/include/gtest/internal/gtest-port.h
googletest/src/gtest.cc
googletest/test/gtest-death-test_test.cc
googletest/test/gtest-filepath_test.cc
googletest/test/gtest-options_test.cc
googletest/test/gtest-port_test.cc
googletest/test/gtest_color_test_.cc
googletest/test/gtest_output_test_.cc
googletest/test/gtest_repeat_test.cc
googletest/test/gtest_unittest.cc

Use gender-neutral pronouns in comments and docs

---

googlemock/docs/CheatSheet.md

Small typo fix in googlemock documentation.

#1282: Doc typo fix

---

googletest/README.md

I had this issue and spent a while trying to figure out how to change the option, only to find that it's already handled in the CMake file.
Judging by some of the comments in issues (e.g. #266) other people have had the same problem.
Therefore, simply added it explicitly to the README at the bottom of the section about integrating with an existing CMake project.

Updated README with C runtime dynamic/static linking issues in Windows info

---

.gitignore
googlemock/test/gmock-generated-matchers_test.cc
googlemock/test/gmock-matchers_test.cc
googletest/cmake/internal_utils.cmake
googletest/include/gtest/internal/gtest-port.h
googletest/test/gtest-printers_test.cc
googletest/test/gtest_catch_exceptions_test_.cc

Allow use C++11 features available in VS2015/2017, fix failed tests with GMock under VC++2015 compiler
This is rebased PR #811
I have been trying to merge this change since February 2016 (PR #723)

VS2015/2017 build fix and enable C++11 features (attempt number three)

---

googlemock/include/gmock/gmock-generated-matchers.h
googlemock/include/gmock/gmock-generated-matchers.h.pump

This removes some simple warnings that I hit when using Gmock with gcc6 and -Wall -Wextra -Werror.

Remove gcc 6 misleading indentations warnings

---

googletest/include/gtest/internal/gtest-port.h

ThreadLocal class needs to be have default visibility.
Root cause is gtest uses typeinfo for the ThreadLocal class.
The problem manifests When gtest/gmock are built as a shared library
with libc++. When a class is used in typeinfo, it must have default
visibility.
There is an explanation about typeinfo and visibility here:
https://developer.apple.com/library/content/documentation/DeveloperTools/Conceptual/CppRuntimeEnv/Articles/SymbolVisibility.html
When libc++ is used with gtest in shared library mode, any tests
that are compiled with -fvisibility=hidden and exercise the
macro EXPECT_CALL, it results in an abort like:
[ FATAL ] /usr/include/gtest/internal/gtest-port.h:1394::
Condition typeid(*base) == typeid(Derived) failed.
This is because the typeinfo for ThreadLocal class is not …

googletest: Add GTEST_API_ attribute to ThreadLocal class.

---

googletest/docs/FAQ.md

remove markdown stars (bold) from code examples

---

googletest/src/gtest.cc

It seems like MinGW's `isatty()` always returns 0, one can therefore not use `--gtest_color=auto`. However,  `--gtest_color=yes` works with this patch and thus resolves #826.

Fix issue #826 by treating MinGW as "non-Windows" when determining colored output

---

googletest/src/gtest-printers.cc

This change speeds up the runtime of a value-parameterized test I have
which has lots of values with large strings full of unprintable
characters by 2x. I profiled it and traced most of the slowness during
googletest startup down to the way String::FormatHexInt was creating and
destroyed a stringstream for each character in the string for each
value.
Originally submitted as google/googletest#830.

Speed up printing of characters which need hex escaping

---

googlemock/CMakeLists.txt
googletest/CMakeLists.txt
googletest/include/gtest/internal/gtest-port.h

Prevent `warning C4996: 'std::tr1': warning STL4002: The non-Standard std::tr1 namespace and TR1-only machinery are deprecated and will be REMOVED.
This commit originates from #1311

Remove C4996 warning in VS2017

---

googlemock/test/BUILD.bazel

Without the directive embedding googletest into third_party breaks any //... target.  For example, trying to add `googletest` as a submodule of [protobuf](https://github.com/google/protobuf) results in:
```console
$ bazel test //...:all
..............
ERROR: /Users/coryan/protobuf-develop/third_party/googletest/googlemock/test/BUILD.bazel:37:1: third-party rule '//third_party/googletest/googlemock/test:gmock_all_test' lacks a license declaration with one of the following types: notice, reciprocal, permissive, restricted, unencumbered, by_exception_only.
ERROR: package contains errors: third_party/googletest/googlemock/test.
ERROR: error loading package 'third_party/googletest/googlemock/test': Package 'third_party/googletest/googlemock/test' contains errors.
INFO: Elapsed time: 1.732s …
```

Add licenses() directive for googlemock/tests.

---

googlemock/CMakeLists.txt
googletest/CMakeLists.txt

Using system includes for the CMake `INTERFACE_INCLUDE_DIRECTORIES` property silences some warnings that cannot be silenced otherwise. For example, when compiling with `-Wpedantic`, `INSTANTIATE_TEST_CASE_P` generates a warning `ISO C++11 requires at least one argument for the "..." in a variadic macro`. I also had some other warnings about signed-unsigned comparison when using `{ASSERT,EXPECT}_EQ` with an integral constant as the second parameter.
This also conforms to the behavior when `find_package(GTest)` is used, which will facilitate changing from a system-wide install to building googletest as part of the project (as the FAQ recommends)

Use system includes

---

googletest/include/gtest/gtest.h

This PR re-enables C4389 as discussed in https://github.com/google/googletest/issues/683#issuecomment-196694742
C4389 was inhibited in commit 4b83461 making behavior inconsistent with other compilers.

Re-enable MSVC++ C4389 warning in CmdHelperEq()

---

googletest/include/gtest/gtest.h

C4800 has since been removed in MSVC 2017, so trying to silence it throws warning C4619 when enabled.
I could also wrap the whole thing in an `_MSC_VER < 1900` ifdef or so. Whichever you prefer.

Avoid warning C4619 in MSVC 2017.

---

googletest/include/gtest/internal/gtest-port.h

On platforms with std::tuple and not std::tr1::tuple, GTEST_HAS_COMBINE
gets turned off when it works fine (due to GTEST_TUPLE_NAMESPACE_).
Elsewhere in the project, several GTEST_HAS_TR1_TUPLE checks
additionally check GTEST_HAS_STD_TUPLE_, so use that formulation.
(The ones that don't are specific to std::tr1::tuple and are followed by
an identical GTEST_HAS_STD_TUPLE_ version underneath it.)
In particular, this fixes testing::Combine on MSVC 2017, which regressed
here:
https://github.com/google/googletest/pull/1348#issuecomment-353879010

Fix testing::Combine on MSVC 2017.

---

googlemock/test/gmock-internal-utils_test.cc
googletest/src/gtest-death-test.cc
googletest/src/gtest-internal-inl.h
googletest/src/gtest-port.cc
googletest/src/gtest-test-part.cc
googletest/src/gtest.cc
googletest/test/gtest-death-test_test.cc
googletest/test/gtest-filepath_test.cc
googletest/test/gtest-options_test.cc
googletest/test/gtest-param-test_test.cc
googletest/test/gtest-port_test.cc
googletest/test/gtest_color_test_.cc
googletest/test/gtest_env_var_test_.cc
googletest/test/gtest_environment_test.cc
googletest/test/gtest_output_test_.cc
googletest/test/gtest_repeat_test.cc
googletest/test/gtest_stress_test.cc
googletest/test/gtest_unittest.cc

gtest/src/gtest-internal-inl.h -- the preprocessor was being used as an
ad-hoc header file visibility mechanism. the mechanism feels outdated and quixotic.

upstreaming cl 124976692

---

googletest/include/gtest/internal/gtest-port.h

I think this the last patch we're carrying for googletest in BoringSSL! :-)
clang-cl is clang for Windows running in MSVC mode. Chromium uses it for Windows builds. clang-cl is weird in that it defines `__clang__` and `_MSC_VER`, but *NOT* `__GNUC__`. This is vaguely analogous to how normal clang defines `__clang__` (what it is) and `__GNUC__` (what it is compatible with).
However, clang-cl still implements most GCC extensions, being clang. Notably, the way to control `-Wformat-literal` is still with `__attribute__((__format__))`. For better error-checking and strict `-Wformat-literal` compatibility (see 53c478d639b8eebd2942e88266610ebc79c541f6), define `GTEST_ATTRIBUTE_PRINTF_` in clang-cl too.

Also define GTEST_ATTRIBUTE_PRINTF_ in clang-cl.

---

googlemock/include/gmock/gmock-matchers.h
googlemock/src/gmock-spec-builders.cc
googlemock/test/gmock-matchers_test.cc
googletest/include/gtest/gtest-param-test.h
googletest/include/gtest/gtest-param-test.h.pump
googletest/src/gtest-death-test.cc
googletest/src/gtest-port.cc
googletest/src/gtest.cc

This makes it easier to use GTest in projects that build with the
-Wmissing-declarations warning.

Pass the -Wmissing-declarations warning.

---

.travis.yml
appveyor.yml

After this change is merged the pull requests will have reduced / faster builds:
- On Travis, only the Linux builds will be scheduled, which rarely have a backlog.
- On AppVeyor, all builds are scheduled, but only the MSVC 2017 builds run.
Regular builds on `master` or any branch execute the full build matrix.  To see the effect look at these builds for a PR:
https://ci.appveyor.com/project/coryan/googletest/build/18
https://travis-ci.org/coryan/googletest/builds/325820471
And compare against the builds for the branch:
https://ci.appveyor.com/project/coryan/googletest/build/16
https://travis-ci.org/coryan/googletest/builds/325587781

Optimize build matrix on pull requests

---

BUILD.bazel
googlemock/test/BUILD.bazel
googletest/test/BUILD.bazel

Recent versions of Bazel on Windows default to `--cpu=x64_windows` instead of `--cpu=x64_windows_msvc`. Tensorflow and Protobuf handle both with two `config_setting`. We should do the same for googletest.

[Bazel] Detect Windows with cpu value x64_windows and x64_windows_msvc

---

googletest/docs/AdvancedGuide.md
googletest/include/gtest/gtest.h
googletest/src/gtest.cc
googletest/test/BUILD.bazel
googletest/test/gtest_assert_by_exception_test.cc

while not losing benefits of EXPECT, and not killing the whole test,
as with --gtest_throw_on_failure.
183822976

Add ability to throw from ASSERT

---

googletest/src/gtest-death-test.cc

As of recently, Google Test fails to compile with the warning below when used in projects with strict warning settings.
googletest/src/gtest-death-test.cc:1004:13: error: unused function 'StackGrowsDown' [-Werror,-Wunused-function]

Fix unused function warning on Mac OS.

---

googletest/docs/Primer.md

Both names must be valid C++ identifiers, and they should not contain underscore (`_`)

TEST() arguments are invalid in an example

---

googletest/include/gtest/internal/gtest-internal.h

Trailing commas are allowed since C99 and C++ standards since. It is not allowed in C++ 98. To make gtest  compatible with C++98 this has to go. It causes issues for some less common compilers.

Removed trailing comma in enum

---

googletest/include/gtest/internal/gtest-port.h
googletest/src/gtest-death-test.cc
googletest/test/gtest_env_var_test.py

Google Test has recently (02/09/2018) switched the default death test style from "fast" to "threadsafe" in https://github.com/google/googletest/commit/ec7faa943d7817c81ce7bdf71a21ebc9244dc8de
Threadsafe death tests have been used internally for a while, and are proven to be a better default.
However, adopting this better default can be challenging for large projects with a significant investment in custom infrastructure built on top of Google Test.  The same custom infrastructure can make it difficult for large projects to switch back to the old default by passing in `--gtest_death_test_style=fast`.
For this reason, the default switch is considered too disruptive, and this PR reverts it. This PR also introduces the `GTEST_DEFAULT_DEATH_TEST_STYLE` preprocesor macro, which replaces the …

Add preprocessor macro for default death test style.

---

appveyor.yml

AppVeyor build servers have two cores, so why not use them?

Add options to parallelize builds.

---

googletest/src/gtest.cc

The full message unlike summary also includes stack trace.

Use a full message in the JSON output for failures

---

googlemock/include/gmock/internal/gmock-internal-utils.h
googlemock/test/gmock-actions_test.cc

This is an attempt at fixing #1476. I don't know where __WCHAR_UNSIGNED__ is and isn't defined, so I tried to make it so that it not being defined maintains existing behaviour.

Try to handle unsigned wchar_t (arm) a bit better

---

googletest/src/gtest.cc

This uses asm("int3") for clang/gcc on x86 as alternative for DebugBreak()

provide alternative for DebugBreak()

---

googlemock/include/gmock/gmock-generated-nice-strict.h.pump

Commit fe402c27790ff1cc9a7e17c5d0aea4ebe7fd8a71 published the changes in internal CL 156157936, but missed the diff in gmock-generated-nice-strict.h.pump. This makes it difficult to reason about the change, because the .pump file is more concise than the generated file.
This PR was tested by re-generating the .h file using the command below and checking the git diff.
```bash
./googletest/scripts/pump.py googlemock/include/gmock/gmock-generated-nice-strict.h.pump
```

Sync gmock-generated-nice-strict.h.pump with gmock-generated-nice-strict.h

---

googlemock/include/gmock/gmock-generated-nice-strict.h
googlemock/include/gmock/gmock-generated-nice-strict.h.pump
googlemock/include/gmock/gmock-spec-builders.h
googlemock/test/gmock-nice-strict_test.cc

Internal CL 156157936, which was published in commit fe402c27790ff1cc9a7e17c5d0aea4ebe7fd8a71, introduced undefined behavior by casting a base class (internal::{Naggy,Nice,Strict}Base<MockClass>, using the curiously recurring template pattern) pointer to a derived class ({Naggy,Nice,Strict}Mock<MockClass>), in the base class' constructor. At that point, the object isn't guaranteed to have taken on the shape of the derived class, and casting is undefined behavior.
The undefined behavior was caught by Chrome's CFI build bot [1], and prevents rolling googletest past that commit / CL.
This commit simplifies the {Naggy,Nice,Strict}Mock class hierarchy in a way that removes the undefined behavior.
[1] https://www.chromium.org/developers/testing/control-flow-integrity

Remove multiple inheritance from "unintesting call" mock classes.

---

googletest/src/gtest.cc
googletest/test/gtest_unittest.cc

Fix the bug where ad_hoc_test_result() functions of UnitTest and TestCase objects would return failures registered at TestCase and UnitTest scopes, respectively.
193382331

Fix a bug with ad_hoc_test_result() functions of UnitTest and TestCase classes

---

googletest/include/gtest/internal/gtest-type-util.h
googletest/include/gtest/internal/gtest-type-util.h.pump
googletest/test/gtest_unittest.cc

Add support for versioned standard libraries.
This canonicalizes demangled names by omitting a nested inline namespace within namespace std if the name of the nested namespace begins with a double underscore.  This improves compatibility with libc++.

Std lib versioning

---

googletest/src/gtest.cc

When we do parallel test execution with a process for a test,
initialization of gtest become performance bottleneck when the test
binary contains many testcases.
Especially, some parameterlized test in chromium browser affected by
largely when address sanitizer is enabled.
Address sanitizer does not allow using optimized strcmp function and
test addition in parameterized test require lookup of test case using
strcmp.
This patch reduces the number of strcmp, it is called when registering
parameterized test. Using reverse iterator improves the time to find
registered tests in such case.
Some tests for chromium browser using address sanitizer finished 2x
faster with this patch.

Reduce the number of strcmp calling while initialization

---

googletest/include/gtest/internal/custom/gtest-port.h
googletest/src/gtest.cc
googletest/test/BUILD.bazel
googletest/test/gtest_testbridge_test.py
googletest/test/gtest_testbridge_test_.cc

This PR makes googletest use the test filtering expression supplied via bazel's "--test_filter" parameter for "bazel run" and "bazel test" commands.
Internal CL is at http://cl/199691997

Support bazel test filtering

---

googletest/include/gtest/internal/gtest-port.h

When I include the gtest.cc to my project and compile it with vs2005 sp1, I got a few of warnings like these :
```
1>..\googletest\include\gtest\internal\gtest-port.h(2489) : warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>        c:\program files (x86)\microsoft visual studio 8\vc\include\string.h(157) : see declaration of 'strncpy'
1>..\googletest\include\gtest\internal\gtest-port.h(2497) : warning C4996: 'chdir': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _chdir. See online help for details.
1>        c:\program files (x86)\microsoft visual studio 8\vc\include\direct.h(127) : see declaration of 'chdir' …
```

VS2005 with SP1(_MSC_VER=1400) already supports __pragma

---

BUILD.bazel
googletest/include/gtest/gtest-printers.h

The BUILD.bazel file was automatically reformatted by `buildifier`.

Adds the UniversalPrinter for absl::variant.

---

BUILD.bazel
googletest/CMakeLists.txt
googletest/cmake/internal_utils.cmake
googletest/src/gtest-internal-inl.h
googletest/src/gtest.cc
googletest/test/BUILD.bazel
googletest/test/gtest_output_test.py
googletest/test/gtest_output_test_golden_lin.txt
googletest/test/gtest_xml_output_unittest.py

This change adds the ability to generate stacktraces in Google Test on
both failures of assertions/expectations and on crashes. The
stacktrace support is conditionally available only when using Abseil
with Google Test.
To use this support, run the test under Bazel with a command like this:
bazel test --define absl=1 --test_env=GTEST_INSTALL_FAILURE_SIGNAL_HANDLER=1 //path/to/your:test
The "--define absl=1" part enables stacktraces on assertion/expectation
failures.
The "--test_env=GTEST_INSTALL_FAILURE_SIGNAL_HANDLER=1" part enables
the signal handler that logs a stacktrace in the event of a crash
(this also requires the "--define absl=1" part). This is not the
default since it may interfere with existing tests.
cl/203813940

Adds stacktrace support from Abseil to Google Test

---

googletest/test/googletest-printers-test.cc

Printers test: fixed compilation bug, due to unnecessary parentheses in declaration

---

googletest/src/gtest-death-test.cc

At present the exception conditions deliberately created by death-tests are not handled by the death-test framework, so the system default exception handler will receive them, causing each death-test to trigger a full stack-trace to be dumped.
This CL makes the following changes:
1. Register an exception port on the child process, and wait on both that and on process termination. If an exception is observed then kill the process directly, to prevent the exception being handled.
2. Fix the death-test implementation for Fuchsia to correctly close the sub-process handle, where previously each death-test leaked a (zombie) process until the parent process exited.
3. Fix initialization of the fdio_spawn_action_t not to use the C-only struct member initialization syntax.
This corresponds to …

Suppress default exception handling

---

googletest/src/gtest-death-test.cc

My previous patch to have death-tests use exception ports acquired a last-minute typo before I uploaded it. >.<

Fix typo breaking Fuchsia build.

---

googletest/docs/advanced.md

There are some bad formatting issues in the advanced.md, @stianval also reported similar issue([1679](https://github.com/google/googletest/issues/1679)).
Many of the break is introduced in this commit(5437926) and looks like to improve the readbility at source code level. However, those markdown table syntax is not supported in github.

Fix the bad format issues in docs/advanced.md

---

CMakeLists.txt
cmake/googletestConfig.cmake.in
googlemock/CMakeLists.txt
googletest/CMakeLists.txt

I _think_ this represents some of the "best practices" for exporting
targets. They'll be available in a `googletest::` namespace (e.g.
`googletest::gmock`) with non-namespaced `ALIAS` targets.
- Added GOOGLETEST_VERSION variable
- Use `CMakePackageConfigHelpers`, bump minimum CMake version to 2.8.8
Signed-off-by: Dakota Hawkins <dakotahawkins@gmail.com>

Improve CMake exported targets

---

googlemock/README.md

This step is no longer necessary and causes configuration errors. The configuration given in the googletest README.md is sufficient to bring in all the googlemock headers.

Fix #1764 Remove cmake code that leads to a configuration error

---

googlemock/CMakeLists.txt
googletest/CMakeLists.txt

To make sure packages are relocatable, use `$<INSTALL_PREFIX>` in `$<INSTALL_INTERFACE:...>` `target_include_directories`.
`$<INSTALL_PREFIX>` was introduced in CMake 2.8.11, which is already being checked for locally.
References:
- https://cmake.org/cmake/help/latest/manual/cmake-packages.7.html#id19
- https://github.com/robotology/how-to-export-cpp-library/blob/claudio/headeronly/src/LibTemplateCMake/CMakeLists.txt#L42
Signed-off-by: Dakota Hawkins <dakotahawkins@gmail.com>

Use `$<INSTALL_PREFIX>` in `target_include_directories`

---

googletest/docs/primer.md

The current link pointed to a non existing section in the FAQ.

Fix broken FAQ link in primer.md

---

googlemock/cmake/gmock.pc.in
googlemock/cmake/gmock_main.pc.in

* GTest is a required dependency for GMock, hence
we always need to pull it in.
@gennadiycivil could we also get this into the `1.8.0` branch? Having the wrong pkg-config files there will set it in stone and make them quasi useless.

pkgconfig: Unconditionally depend on GTest when using GMock

---

googletest/test/gtest_unittest.cc

The unused attribute was removed with commit 3299a23 on 2018-02-23, but it currently breaks build of 1.8.1, because of -Werror GCC parameter as reported in issue #1825.

Return GTEST_ATTRIBUTE_UNUSED_ on record_property_env

---

googletest/include/gtest/internal/gtest-internal.h
googletest/test/gtest_unittest.cc

Just like #911 this PR aims to output the message of a std::exception in case of a failure.

Added special catch for std::exception in GTEST_TEST_NO_THROW_

---

googletest/include/gtest/internal/gtest-port-arch.h
googletest/test/gtest_unittest.cc

[msys] fix unittest ColoredOutputTest.UsesColorsWhenTermSupportsColors

---

googletest/xcode/Config/General.xcconfig

In support of issue: https://github.com/google/googletest/issues/1854
Tested in: Xcode 10 (10A255) - September 17, 2018

Issue #1854: remove support for i386 for XCode 10

---

appveyor.yml

Reverts google/googletest#1853
This causes errors 
cmake.exe : C:/mingw-w64/i686-6.3.0-posix-dwarf-rt_v5-rev1/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.3.0/../../../../i686-w64-mingw32/bin/as.exe: CMakeFiles\gmock-matchers_test.dir\test\gmock-matchers_test.cc.obj: too many 
sections (54707)
At line:17 char:1
+ & cmake --build . --config $env:configuration -- $cmake_parallel
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (C:/mingw-w64/i6...ections (54707):String) [], RemoteException
+ FullyQualifiedErrorId : NativeCommandError
C:\Users\appveyor\AppData\Local\Temp\1\ccIA2Doy.s: Assembler messages:
C:\Users\appveyor\AppData\Local\Temp\1\ccIA2Doy.s: Fatal error: can't write 220 bytes to section .text of …

Revert "[mingw] enable the unittests for gmock and gtest again"

---

CMakeLists.txt

This pull request should fix a build issue that was mentioned in issue [#1865](https://github.com/google/googletest/issues/1865). I added C++11 as a standard to the root CMakeLists.txt file. As a result, the build not longer fails and succeeds.

Add C++11 standard in the root CMakeLists.txt

---

googlemock/include/gmock/gmock-spec-builders.h

I compile with all warnings as errors, and these changes fix the implicit casting that generate warnings in my unit tests.  With these changes I will get no warnings and thus will be able to turn on warnings as errors in my unit tests.

Change types to remove cast warnings.

---

googletest/src/gtest.cc

`some_executable_with_gtest_main.exe --help` says:
```
--gtest_output=(json|xml)[:DIRECTORY_PATH/|:FILE_PATH]
Generate a JSON or XML report in the given directory or with the given
file name. FILE_PATH defaults to test_details.xml.
```
But `kDefaultOutputFile` is defined as:
```c++
// The default output file.
static const char kDefaultOutputFile[] = "test_detail";
```
This PR fixes XML file name in help message.
Issue: #1910

Fix incorrect XML file name in help message

---

googletest/README.md

Per #1883, builds of Google Test may fail if the version C++ is not manually
set to C++11 during the build process.

add documentation of manual c++11 specification

---

googletest/README.md

Fixes #1639
Change CMAKE_BINARY_DIR to CMAKE_CURRENT_BINARY_DIR
Able to use in a subfolder's CMakeLists.txt

Change CMake googletest download location in docs

---

googlemock/include/gmock/gmock-spec-builders.h
googlemock/src/gmock-spec-builders.cc
googlemock/test/gmock-generated-function-mockers_test.cc
googlemock/test/gmock-matchers_test.cc
googlemock/test/gmock_link_test.h
googletest/include/gtest/gtest-message.h
googletest/include/gtest/internal/gtest-death-test-internal.h
googletest/include/gtest/internal/gtest-internal.h
googletest/include/gtest/internal/gtest-port.h
googletest/src/gtest-death-test.cc
googletest/src/gtest-filepath.cc
googletest/src/gtest-port.cc
googletest/src/gtest.cc
googletest/test/googletest-test-part-test.cc
googletest/test/gtest_unittest.cc

Resolves #1323
C++98 is dropped in the master so this PR shouldn't be harmfull.

fix #1323 : Replace NULL macro with nullptr

---

googlemock/docs/CheatSheet.md

The Optional() matcher is otherwise undocumented except in the source.
This patch adds it to the cheat sheet for better visibility.
Fixes #1644.

Add Optional() to the cheat sheet doc.

---

googletest/make/Makefile

Added a line to the sample Makefile in googletest/googletest/make to specify the use of C++11 in CXXFLAGS as required by googletest. This flag is required on some systems to make sure C++11 is used and it should be automatically included in the sample Makefile in order for it to run out of the box.

Updating Sample Makefile to Specify C++11

---

googlemock/include/gmock/gmock-matchers.h
googlemock/include/gmock/internal/gmock-port.h
googlemock/src/gmock-spec-builders.cc
googlemock/test/gmock-actions_test.cc
googlemock/test/gmock-generated-function-mockers_test.cc
googletest/cmake/internal_utils.cmake
googletest/include/gtest/internal/gtest-internal.h
googletest/include/gtest/internal/gtest-port.h
googletest/src/gtest.cc
googletest/test/gtest_unittest.cc

Since the readme states that MSVC 2015 or later is a requirement, it might make sense to delete all of the workarounds for older versions and bump the version check in `googlemock/include/gmock/internal/gmock-port.h` to match the readme.
I also noticed that the pragma warning disable in `googlemock/test/gmock-actions_test.cc` has different conditions for when to push and when to pop, so now they're the same (`_MSC_VER == 1900`). If you want to keep the workarounds for older MSVC versions, I can open a PR with just the pragma warning fix.
There's also some mention of Windows CE which I wasn't sure what to do with. It should probably also be deleted since that platform's been end-of-life for a long time now.

Remove old MSVC workarounds

---

googletest/cmake/internal_utils.cmake

I think Googletest should not set `THREADS_PREFER_PTHREAD_FLAG` on its own. 
- If you link a CUDA-enabled language against a gtest on a machine where CMake detects -pthread, this will not compile because the flags is propagated to the CUDA target, but the flag is not recognized by nvcc. On this machine, we don't want the pthread flag. This is probably not that important as this is a general CMake problem and will be fixed with new CMake Versions (there are many issues, e.g. https://gitlab.kitware.com/cmake/cmake/merge_requests/2529 for MPI and many others).
- More importantly, if you do `find_package(Threads)` already before adding googletest, this will lead to strange behaviour: The first cmake pass will do the find_package(Threads) with the option disabled (or whatever the user …

Issue #1955: Remove THREADS_PREFER_PTHREAD_FLAG

---

googletest/include/gtest/internal/gtest-port.h

Do not define GTEST_IS_THREADSAFE within GTEST_HAS_SEH

---

.gitignore
library.json

There was a trailing comma in the library.json file that was causing it to be malformed.
I also added .vs directory to .gitignore to ignore Visual Studio working files.

Correct library.json syntax

---

googlemock/Makefile.am
googletest/Makefile.am

I made a few updates to the Makefile.am files so that "make dist"
succeeds and produces a usable tarball. We need this for protobuf
because the protobuf tarballs include a bundled copy of googletest.

Fixed "make dist"

---

googlemock/include/gmock/gmock-matchers.h

The issue still exists in 1.8.1 and NOT in master branch. It was introduced to 1.8.1 only by #1512.
This code
GTEST_COMPILE_ASSERT_(
!IsHashTable<GTEST_REMOVE_REFERENCE_AND_CONST_(LhsContainer)>::value,
use_UnorderedPointwise_with_hash_tables);
Creates 2nd variable use_UnorderedPointwise_with_hash_tables.

Fix for: failed build on centos6 master #1587

---

WORKSPACE
googletest/cmake/internal_utils.cmake
googletest/include/gtest/internal/gtest-port.h

Currently, 1.8.x does not compile using MSVC 1700 and WINCE800 aka. Windows Embedded Compact 2013. Use `-DGTEST_USE_OWN_TR1_TUPLE=1 -DGTEST_HAS_TR1_TUPLE=0` to compile. 
I hope that this is considered critical as it does not compile for the platform. 
Some of the errors:
```
error C2440: 'reinterpret_cast' : cannot convert from 'int' to 'int'
error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
error C2061: syntax error : identifier 'LPCWSTR'
```

Add missing typedefs for WINCE800 (Windows Embedded Compact 2013)

---

googletest/README.md

Fix the **include/gtest/internal/gtest-port.h** link in the `Tweaking Google Test` title

Fix README.md broken link

---

googletest/docs/advanced.md

This is just a mistake in the document. Google Test doesn't output
such an invalid JSON report.

Fix an invalid example of JSON report in advanced.md

---

.travis.yml
ci/env-osx.sh
ci/install-osx.sh

This will help ensure that test coverage isn't missed when changes that
can impact OSX with clang are submitted. Although not perfect, testing
changes on OSX with clang is an ok proxy [for now] for testing changes on
FreeBSD with clang (testing on FreeBSD is non-trivial, as Travis CI doesn't
support operating systems other than Linux and OSX).
In order to support this, install the packages via homebrew using a
`addons::homebrew::packages` block (similar to `addons::apt::packages`
for Ubuntu), as documented in the Travis CI docs
( https://docs.travis-ci.com/user/installing-dependencies/ ). While
here, try pushing apt* calls into the Travis config for Ubuntu, instead
of delaying the equivalent calls in the `ci/*.sh` scripts. Keep the
`ci/*.sh` scripts for ease of testing locally (and extend …

Test out changes with clang/OSX each PR using Travis CI

---

googletest/CMakeLists.txt

Signed-off-by: Knut Omang <knut.omang@oracle.com>

Set gtest version correctly for older cmake versions

---

googlemock/test/gmock-matchers_test.cc
googletest/test/googletest-param-test-test.cc

Provide dummy accessors for private values that are set in initializers,
but not actually used.

Fix -Wunused-private-field issues with clang

---

googletest/src/gtest.cc

If the object was never created then trying to call &Test::DeleteSelf_
will dereference a null pointer, with undefined behaviour.
Fixes #845

Stop TestInfo::Run() calling a function through null pointer

---

googlemock/test/gmock-matchers_test.cc

`MatchAndExplain(..)` in `gmock-matchers_test` overrides a virtual method.
Remove the `virtual` keyword and apply `override` to it instead.

Fix clang `-Winconsistent-missing-override` warnings

---

googlemock/test/gmock-generated-matchers_test.cc
googlemock/test/gmock-matchers_test.cc

Comment out unused method parameters in their relevant definitions.

Fix clang `-Wunused-parameter` warnings

---

BUILD.bazel
appveyor.yml

While the google test library is being built as a shared library using Bazel,
so that there is a rule like
cc_test(
name = "iterator_traits_test",
linkstatic = 0,
deps = ["@gtest//:gtest_main"],
...
)
in a BUILD file, the following error appears on Windows:
INFO: Found 1 test target...
ERROR: C:/../external/gtest/BUILD.bazel:55:1: output 'external/gtest/gtest.if.lib' was not created
ERROR: C:/../external/gtest/BUILD.bazel:55:1: not all outputs were created or valid
Target //test:iterator_traits_test failed to build
The reason is a missing "win_def_file" attribute of the "gtest" and
"gtest_main" rules in the BUILD.bazel inside the google test library
package.
The "windows_export_all_symbols" feature is added to the rules, this
feature forces Bazel to export all symbols from the google test …

Enable building as a shared library (dll) on Windows with Bazel

---

googletest/cmake/internal_utils.cmake

clang++ compilation when `-Wsign-conversion` is currently broken and the
issues within the code are varied and widespread. For the time being
ignore `-Wsign-conversion` issues, even though some of them are valid
and bleed over into issues that would be found with
`-Wtautological-compare`, et al.

Ignore `-Wsign-conversion` issues

---

googletest/test/googletest-death-test_ex_test.cc

Due to some caveats in the FreeBSD build system and the fact that the
source file is used to compile 2 different death tests with different
flags, I needed (as a shortterm workaround) to copy the test to 2
differently named files.
While this works for compiling the test, as I discovered, this doesn't
work with running `CxxExceptionDeathTest.PrintsMessageForStdException`,
as the testcase hardcodes `googletest-death-test_ex_test.cc`. Use `__FILE__`
when looking for failures, as opposed to looking for the hardcoded name as it
can vary depending on how the test was built.

Don't hardcode the filename in `CxxExceptionDeathTest.PrintsMessageForStdException`

---

googletest/docs/primer.md

This fixes a small grammatical mistake in the documentation.

Fix grammatical error in primer.md

---

googlemock/CMakeLists.txt

Building all test binaries under their respective subtrees makes
building the project via cmake easier to grok without additional hacks.
In particular, when dealing with the conversion I proposed in
https://reviews.freebsd.org/D19430 (switching from autotools to cmake),
I ran into unexpected gtest prefixing under the googlemock directory, as
opposed to the googletest directory. Example:
Before: `googlemock/gtest/googletest-break-on-failure-unittest_`
After:  `googletest/googletest-break-on-failure-unittest_`
The latter form is easier to translate to packaging manifests and will
remain consistent with the `GMOCK_BUILD=BOOL:false` based builds.

Prefix googletest binaries under its own subtree instead of `gtest`

---

googletest/CMakeLists.txt
googletest/Makefile.am
googletest/docs/advanced.md
googletest/src/gtest.cc
googletest/test/BUILD.bazel
googletest/test/gtest_skip_in_environment_setup_test.cc

gtest prior to this change would completely ignore `GTEST_SKIP()` if
called in `Environment::SetUp()`, instead of bailing out early, unlike
`Test::SetUp()`, which would cause the tests themselves to be skipped.
The only way (prior to this change) to skip the tests would be to
trigger a fatal error via `GTEST_FAIL()`.
Desirable behavior, in this case, when dealing with
`Environment::SetUp()` is to check for prerequisites on a system
(example, kernel supports a particular featureset, e.g., capsicum), and
skip the tests. The alternatives prior to this change would be
undesirable:
- Failing sends the wrong message to the test user, as the result of the
tests is indeterminate, not failed.
- Having to add per-test class abstractions that override `SetUp()` to
test for the capsicum feature set, …

Handle GTEST_SKIP() when calling `Environment::SetUp()`

---

googlemock/include/gmock/gmock-matchers.h
googletest/include/gtest/gtest-matchers.h

Per the MSVC documentation, the warning is new as of Visual Studio 2017, version 15.8.
https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/c5046?view=vs-2019
GTest users building on MSVC 2015 or older versions of 2017 will, when C4616 is enabled, see a warning like:
[...]gtest-matchers.h(53): error C2220: warning treated as error - no 'object' file generated
[...]gtest-matchers.h(53): warning C4619: #pragma warning: there is no warning number '5046'
Guard the mention of 5046 by an _MSC_VER check. VS2017 15.8 corresponds to an _MSC_VER of 1915.
https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=vs-2019
VS2017 15.7 is not very old (15.7 was released August 2018 and 15.8 was released November 2018), and I believe VS2015 is still covered under Abseil's …

MSVC C5046 warning is unavailable in MSVC 2015.

---

googletest/include/gtest/internal/gtest-port.h

Fixes a minor ordering issue when defining the platform macro.
Also fixes a minor typo: 'Max OS X' -> 'Mac OS X'.

Sort Haiku platform definition alphabetically.

---

googletest/src/gtest-port.cc
googletest/src/gtest-printers.cc

Some Windows users builds were broken after a0d60be. This change
addresses the lingering -Wsign-conversion issues with those platforms
by adding some missing `static_cast` calls as needed.

Address fallout from -Wsign-conversion work on Windows

---

googletest/CMakeLists.txt

Hi here is a fix to allow google test cmake to works on CentOS 7. On this cmake VERSION was not mendatory.
user > uname -a 
Linux localhost.localdomain 3.10.0-957.10.1.el7.x86_64 #1 SMP Mon Mar 18 15:06:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
user > cmake -v
cmake version 2.8.12.2
Best Regards,

Fix compilation on CentOS 7

---

googletest/src/gtest-printers.cc

Google Test build is broken on Android by the following error:
```
~/googletest/googletest/src/gtest-printers.cc:240:43: error:
implicit conversion changes signedness: 'wchar_t' to 'int' [-Werror,-Wsign-conversion]
*os << ", 0x" << String::FormatHexInt(static_cast<UnsignedChar>(c));
~~~~~~               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
~/googletest/googletest/src/gtest-printers.cc:255:3: note: in
instantiation of function template specialization 'testing::internal::PrintCharAndCodeTo<wchar_t,
wchar_t>' requested here
PrintCharAndCodeTo<wchar_t>(wc, os);
^
1 error generated.
```
I fixed it by using `FormatHexUInt32` instead of `FormatHexInt`. After all, UnsignedChar is intended to be an unsigned type.

Fix -Wsign-conversion error on Android by using the right function

---

googletest/include/gtest/gtest-printers.h
googletest/test/googletest-overload-addressof-operator-test.cc

Otherwise the code won't compile if the '&' operater is overloaded and
return something that cannot be casted to void *.

Use std::addressof to instead of plain '&'.

---

CMakeLists.txt
Makefile.am
configure.ac
googlemock/CMakeLists.txt
googlemock/Makefile.am
googlemock/configure.ac
googletest/CMakeLists.txt
googletest/Makefile.am
googletest/configure.ac

Fix typo introduced in 63be3dcc245 (maintaners -> maintainers)

---

googletest/src/gtest.cc

windows msvc toolchain with werror and wconversion
will break if converting long to DWORD.

unbreak windows build

---

CMakeLists.txt

As suggested in #2150.
This moves the `cmake_policy` command before the project definition, where it used to be until: https://github.com/google/googletest/commit/67265e07067758f51db6fd9296de02c16b1f9873. It was introduced with https://github.com/google/googletest/pull/782. 
This suppresses the following policy warning:
```
CMake Warning (dev) at CMakeLists.txt:6 (project):
Policy CMP0048 is not set: project() command manages VERSION variables.
Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
command to set the policy and suppress this warning.
The following variable(s) would be set to empty:
CMAKE_PROJECT_VERSION
CMAKE_PROJECT_VERSION_MAJOR
CMAKE_PROJECT_VERSION_MINOR
CMAKE_PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress …
```

Suppress CMake policy warning (CMP0048)

---

googlemock/include/gmock/internal/gmock-internal-utils.h

GCC-9 now treats `signed wchar_t` and `unsigned wchar_t` as ill-formed.
Only define `GMOCK_HAS_SIGNED_WCHAR_T_` if `__GNUC__ < 9`.
Resolves https://github.com/google/googletest/issues/2269

Don't allow signed/unsigned wchar_t in gcc 9 and later

---

googletest/scripts/fuse_gtest_files.py

`gtest-spi.h` is what contains the [testing utilities for expanding](https://github.com/google/googletest/blob/master/googletest/docs/advanced.md#catching-failures) googletest.  Currently it is fused into the source file, but this prevents users of the fused files from using those utilities directly.
I changed the fused script to put it in the header instead.  Let me know what you think!

Fuse gtest-spi.h into the resulting header.

---

googletest/cmake/internal_utils.cmake

This allows to use the string "SHARED" without interpreting it as a variable. Resolves issue #2282.

Setting cmake CMP0054 policy to NEW

---

googletest/docs/primer.md

According to the nomenclature, what was called a test case
is actually a test suite

docs/primer: Fixed usage of test case

---

googletest/docs/advanced.md
googletest/docs/faq.md

Replace go links with externally accessible urls.

Remove google internal links from documentation on github

---

googlemock/docs/cook_book.md

This line directly contradicts the warning that google mock spits out on unused mock calls:
```
NOTE: You can safely ignore the above warning unless this call should not happen.  Do not suppress it by blindly adding an EXPECT_CALL() if you don't mean to enforce the call.  See https://github.com/google/googletest/blob/master/googlemock/docs/CookBook.md#knowing-when-to-expect for details.
```
One or the other should be changed, and I believe the advice in this file is incorrect.

Fix bad advice in cook book

---

googlemock/docs/cook_book.md

ee3aa831172090fd5442820f215cb04ab6062756 added a broken link
which results in 404. The broken part is reference to a
nonexistent file "CheatSheet.md" instead of "cheet_sheet.md".
In addition, since the aforementioned link references the same file,
it is sufficient to provide a relative reference to itself rather than
forcing a user to connect to github.com.

Fix a broken link

---

googlemock/include/gmock/gmock-spec-builders.h

gmock-spec-builders.h uses std::function (in MockFunction) but did not include <functional> to provide it. Apparently, it worked since the header must have been included by something else but better be safe than sorry.
Note that this PR comes from #2319.

Add missing <functional> include

---

googlemock/CMakeLists.txt
googletest/CMakeLists.txt

Building the project on Cygwin fails due to a too large object file. Cygwin is not considered MinGW even if it shares ]options. Along with that two other cases where only MinGW was checked were updated as well.
Note that this PR comes from #2319.

Correct CMake to cover Cygwin

---

googlemock/include/gmock/gmock-generated-actions.h
googlemock/include/gmock/gmock-generated-actions.h.pump
googlemock/include/gmock/gmock-generated-matchers.h
googlemock/include/gmock/gmock-generated-matchers.h.pump

As requested in #2344.
This removes the TODO-ish comments of:
> we'll consider supporting using ACTION*() inside a function.
and
> we'll consider supporting using MATCHER*() inside a function.
My reasoning is:
* Actions can be easily changed to lambdas (or even generic ones if someone uses C++14) so no need to put effort into legacy functionality
* Matchers have also alternatives, e.g. Truly(). Perhaps I should add something like:
> Users are free to provide their local functors and invoke Truly() on them
What do you think (especially about the latter)?

Update pre-C++11 paragraphs

---

googletest/docs/primer.md

Formatting in primer.md

---

googletest/include/gtest/internal/gtest-param-util.h
googletest/test/googletest-output-test-golden-lin.txt
googletest/test/googletest-output-test_.cc

This is useful to let a subsystem generate test names based on parameterized tests
without exposing them as such to the user.
Signed-off-by: Knut Omang <knut.omang@oracle.com>

Remove / from parameterized test names if base test name is empty

---

googlemock/include/gmock/gmock-spec-builders.h

The private mutable member of MockFunction cannot be reached from outside and all its
non-static member functions are not const. Alternatively, we could add const to every function of MockFunction, though it's a much worse idea I believe.
@adambadura - watch out, this will conflict with your #2350 if this gets merged first.

Remove an excessive mutable type specifier

---

googletest/include/gtest/gtest-typed-test.h

Since we started using C++11 this no longer holds true.

Remove an outdated comment

---

googlemock/CMakeLists.txt

Another target fails on Cygwin with the too big file issue. This time it is `gmock-generated-matchers_test`. To get rid of the problem I just used `-Wa,-mbig-obj` for all Google Mock test targets instead of only the failing ones.

Use -Wa,-mbig-obj for Cygwin/MinGW always

---

BUILD.bazel
WORKSPACE
appveyor.yml
googlemock/test/BUILD.bazel
googletest/test/BUILD.bazel

Fixes googletest for upcoming `--incompatible_load_cc_rules_from_bzl` (https://github.com/bazelbuild/bazel/issues/8743) and `--incompatible_load_python_rules_from_bzl` (https://github.com/bazelbuild/bazel/issues/9006).
This change was automatically generated with
`buildifier -lint=fix -warnings=all $(find . -name "BUILD" -o -name "BUILD.bazel" -o -name "*.bzl")`.

Prepare for Bazel incompatible changes

---

googlemock/include/gmock/internal/gmock-internal-utils.h

Googlemock reimplements this unnecessarily.

Reuse IndexSequence from googletest

---

googlemock/include/gmock/internal/gmock-internal-utils.h

It's nowhere used and it's similar to `StaticAssertTypeEq`.

Remove a dead metafunction

---

googlemock/include/gmock/gmock-matchers.h

Hi @zhangxy988,
I've applied some fixes as requested by @EricWF, but they weren't merged into master.

Post-review to #2396

---

googlemock/cmake/gmock.pc.in
googlemock/cmake/gmock_main.pc.in
googletest/cmake/gtest.pc.in
googletest/cmake/gtest_main.pc.in
googletest/docs/pkgconfig.md

Hi @gennadiycivil 
the pkg-config change from last october breaks valid `GNUInstallDirs` uses as discussed in https://github.com/google/googletest/commit/095b3113e7438fd0be901e20b40d376bcd8ef860#r35373291
This reverts the change and adds documentation how to use pkg-config in a cross-compilation setting.

Fix gnu install dirs pkg config

---

googlemock/src/gmock-spec-builders.cc
googletest/src/gtest-test-part.cc

This will fix null file names potentially crashing the program.
Fixes #819 as well.

Use FormatFileLocation for streaming file and line

---

googlemock/include/gmock/gmock-matchers.h
googlemock/include/gmock/internal/gmock-internal-utils.h
googlemock/test/gmock-internal-utils_test.cc
googletest/docs/advanced.md
googletest/include/gtest/gtest.h

Leftovers from improperly closed manual reviews.

Merge stuff that has been given up by manual merges

---

googletest/include/gtest/internal/gtest-port.h

1st commit removes GTEST_HAS_STD_STRING. I think we can drop it, after all it's 2019 :)
2nd commit simply removes usings from the header, which is how all guidelines say
Both changes are backward incompatible. I would merge them though because README.md says the following about [post 1.8.x releases](https://github.com/google/googletest#post-18x):
> On-going work to improve/cleanup/pay technical debt
and we don't quite need it, right?

Remove GTEST_HAS_STD_STRING

---

googlemock/include/gmock/gmock-generated-actions.h
googlemock/include/gmock/gmock-generated-actions.h.pump
googlemock/include/gmock/gmock-generated-matchers.h
googlemock/include/gmock/gmock-generated-matchers.h.pump
googletest/include/gtest/gtest-typed-test.h
googletest/include/gtest/internal/gtest-port.h
googletest/test/gtest_unittest.cc

Mark more functions with "override" keyword, just like
it was done in commit 2460f97152c.
This should prevent compiler from complaining while compiling both
user code, and the googletest code itself with the -Wsuggest-override
option turned on; with the exception of:
* calls to new MOCK_METHOD() in test/gmock-function-mocker_test.cc
* calls to old MOCK_METHODx()/MOCK_CONST_METHODx() in other
unit test files.
Closes #2493

Add more override keywords

---

googlemock/test/gmock-generated-matchers_test.cc
googlemock/test/gmock-matchers_test.cc
googletest/include/gtest/internal/gtest-port.h

This macro didn't work when an array was passed to a function by pointer,
in which case the information about its size was lost.
Better alternatives are:
* std::extent<T>::value (compile-time)
* std::array<T, N>::size() (compile-time)
* std::distance(std::begin(array), std::end(array)) (run-time)

Remove GTEST_ARRAY_SIZE_

---

googletest/CMakeLists.txt
googletest/include/gtest/gtest.h
googletest/src/gtest.cc
googletest/test/BUILD.bazel
googletest/test/gtest_skip_check_output_test.py
googletest/test/gtest_skip_test.cc

Closes #2208
Previously, skip messages were invisible, so debugging skips was hard.
Now we have this:
```
$ ./googletest/gtest_skip_test
Running main() from /home/lesha/github/snarkmaster/googletest/googletest/src/gtest_main.cc
[==========] Running 3 tests from 2 test suites.
[----------] Global test environment set-up.
[----------] 1 test from SkipTest
[ RUN      ] SkipTest.DoesSkip
/home/lesha/github/snarkmaster/googletest/googletest/test/gtest_skip_test.cc:38: Skipped
skipping single test
[  SKIPPED ] SkipTest.DoesSkip (0 ms)
[----------] 1 test from SkipTest (1 ms total)
...
```

[googletest] Output skip message

---

googlemock/include/gmock/internal/gmock-pp.h
googlemock/test/gmock-function-mocker_test.cc
googlemock/test/gmock-pp_test.cc

Should fix #2490 and the errors after #2498 was merged.
The good news is we no longer need `GMOCK_PP_INTERNAL_USE_MSVC` 😄 
~Also see [this Godbolt link](https://godbolt.org/z/KOBAn2) which shows everyone agrees on the preprocessed output after this change (on MSVC, it's printed to `stdout`, so scroll to the bottom of the `stdout` output)~ (Stale now, but we're taking the same approach)

Workaround MSVC __VA_ARGS__ weirdness

---

googlemock/include/gmock/gmock-actions.h
googlemock/test/gmock-actions_test.cc

Prevent using ReturnRef on reference to temporary

---

googletest/include/gtest/gtest-printers.h
googletest/include/gtest/gtest.h
googletest/include/gtest/internal/gtest-port.h
googletest/src/gtest.cc
googletest/test/googletest-printers-test.cc
googletest/test/gtest_unittest.cc

Resolves #2451.
Additionally I've moved it to gtest-internal.h because it requires no porting to specific platforms (long long int is a part of C++11).

Remove BiggestInt

---

googlemock/cmake/gmock.pc.in
googlemock/cmake/gmock_main.pc.in
googletest/cmake/gtest.pc.in
googletest/cmake/gtest_main.pc.in

Remove the threads link library variable references from the pkg-config
Cflags: field, removing -lpthread(s) from the compile flags.
"-l*" linker flags should only be part of the Libs: section and should
not be part of the Cflags: section in pkg-config files.
This was first suggested in
https://github.com/google/googletest/pull/2006 and further discussed in
https://github.com/google/googletest/pull/2483 .

pkg-config: Remove pthread link flag from Cflags

---

googletest/scripts/gen_gtest_pred_impl.py

After 7bd4a7f3 [gtest_pred_impl_unittest.cc](https://github.com/google/googletest/blob/8697709e0308af4cd5b09dc108480804e5447cf0/googletest/test/gtest_pred_impl_unittest.cc) used to be newer than its template.
Sorry, I haven't checked it out before :)

Update documentation from "iff" to "if and only if" in gen_gtest_pred_impl.py

---

googletest/src/gtest.cc

The release v1.10.0 does support only  MVS on Windows. So this fix support again other platforms like MinGW on Windows. It resolve also Issue #2418. 
Feel free to test it.
Suggestion when it will merged: make a new Bugfix Release: v1.10.1 with support of MinGW.

Fix Issue #2418

---

googletest/include/gtest/internal/gtest-internal.h

googletest 1.10.0 fails to compile on msvc version 19.00.23917
with one compilation error:
src\googletest\include\gtest\internal\gtest-internal.h(1188) : error C2039:
'FlatTupleBase<testing::internal::FlatTuple<bool,bool>,testing::internal::IndexSequence<0,1> >':
is not a member of 'testing::internal::FlatTuple<bool,bool>'
This PR fixes the compilation error by explicitly specifying the full type that Indices is
located in the base type.

Fix FlatTuple compilation on older msvc.

---

googlemock/include/gmock/gmock-matchers.h

I strongly advise to enable some sort of "skip whitespace changes" when reviewing this diff.

Remove Nokia's Symbian compiler workaround: SafeMatcherCastImpl

---

googlemock/src/gmock_main.cc
googletest/src/gtest_main.cc

Two commits here:
298a40f0 - removing workaround to the bug that has been patched
a909becd - just me secretly trying to smuggle some unification to both main files

Remove MSVC workaround: wmain link error

---

googlemock/include/gmock/gmock-actions.h

This is a workaround, for those who have to compile with v141 build tools,
for a bug in msvc that the compiler can't compile the WithArgsAction.
see the following link for more details:
https://developercommunityapi.westus.cloudapp.azure.com/content/problem/420339/googlemocks-withargs-doesnt-compile-with-permissiv.html
This fixes #2582

Fix compile break for Microsoft Visual Studio 2017 v141

---

googlemock/src/gmock_main.cc
googletest/src/gtest_main.cc

Turns out that the bug fixed in Visual Studio 2010 is still present in Visual Studio 2014. This was found in #2608.

Revert #2596

---

googlemock/include/gmock/gmock-spec-builders.h

I didn't have a problem with that even after adding /we4355 which would turn all 4355 warnings into errors.

Remove MSVC workaround: warning 4355

---

googletest/test/gtest_unittest.cc

```c++
// To work around a bug in gcc 2.95.0, there is intentionally no
// space after the first comma in the previous statement.
```
Because in the past someone forgot to remove these.
```c++
// Some older GCC versions may issue a spurious warning in this or the next
// assertion statement. This warning should not be suppressed with
// static_cast since the test verifies the ability to use bare NULL as the
// expected parameter to the macro.
```
No problems found. I assume this isn't a problem any longer.

Remove stale comments about older GCC versions

---

googletest/include/gtest/gtest-param-test.h
googletest/include/gtest/internal/gtest-internal.h
googletest/include/gtest/internal/gtest-param-util.h
googletest/test/googletest-output-test-golden-lin.txt
googletest/test/googletest-output-test_.cc
googletest/test/gtest_unittest.cc

Reverted commits:
- 20b5b8ecc7a81d23b4716e22a2b35fd53379c8c6: "Googletest export": disallow empty prefix
- 4c25e2b87fcb78abcfdee2739db9ed7a19754cd3: "Googletest export": Remove test for empty prefix
Reason for revert: Breaks existing applications, such as ANGLE (angleproject.org), requires adding an extra prefix that needs to be typed for no reason (when testing from command line) and increases the logs' sizes by a non-trivial amount due to the very large number of tests ANGLE runs.
The original commit that disallowed empty test prefixes says:
> Add a compile time check to ensure that the parameters to TEST_P and INSTANTIATE_TEST_SUITE_P are not empty. Some compilers already fail in that case and, even where it works, it's likely to result in technically invalid code by virtue of creating …

Revert change that disallows empty test prefixes

---

library.json

Removing exclusion of *-main and*-all targets from the library.json used on platformio.
Closes #2671

Remove exclusion of *-main and*-all targets

---

googlemock/test/gmock-matchers_test.cc

This fixes unit test failure in gmock-matchers_test.cc when compiled using latest VS 2019 on Windows : 
[ RUN      ] PredicateFormatterFromMatcherTest.NoShortCircuitOnFailure
..\..\..\googlemock\test\gmock-matchers_test.cc(6889): error: Expected equality of these values:
expect
Which is: "Value of: dummy-name\nExpected: [DescribeTo]\n  Actual: 1, [MatchAndExplain]"
result.message()
Which is: "Value of: dummy-name\nExpected: [DescribeTo]\n  Actual: 1 (of type enum testing::gmock_matchers_test::`anonymous namespace'::PredicateFormatterFromMatcherTest::Behavior), [MatchAndExplain]"
With diff:
@@ -1,3 +1,3 @@
Value of: dummy-name
Expected: [DescribeTo]
-  Actual: 1, [MatchAndExplain]
+  Actual: 1 (of type enum testing::gmock_matchers_test::`anonymous …

Fix unit test failure on NoShortCircuitOnFailure and DetectsFlakyShortCircuit when GTEST_HAS_RTTI is 1

---

googletest/src/gtest.cc

Fixed warnings

---

googletest/include/gtest/internal/gtest-port.h

Exposition of the problem:
```
> cat main.cpp
#include "gtest/gtest.h"
TEST(errnoTest, errnoTest)
{
ASSERT_EQ(errno, 0);
}
int main(int argc, char** argv)
{
::testing::InitGoogleTest(&argc, argv);
return RUN_ALL_TESTS();
}
```
Compiled with gcc 10 like this:
`> g++ -pthread -o runtest main.cpp -Wl,-Bstatic -lgtest -Wl,-Bdynamic`
Before patch:
```
>  ./runtest
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from errnoTest
[ RUN      ] errnoTest.errnoTest
[       OK ] errnoTest.errnoTest (0 ms)
[----------] 1 test from errnoTest (0 ms total)
[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (0 ms total)
[  PASSED  ] 1 test.
```
(output is colored, I run this inside an interactive …

Make sure IsATTY does not clobber errno.

---

googlemock/include/gmock/gmock-spec-builders.h
googlemock/test/gmock-function-mocker_test.cc

`MocFunction` is slightly changed to transform its argument through (added in this change) `SignatureOf` meta-function. The meta-function extracts the function signature type from the provided type. Thanks to this approach `MockFunction<F>` can now be used with `F` being both function signature (like `bool(int)`) and `std::function` (like `std::function<bool(int)>`).
Besides the immediate benefit, extra extensibility is added. Library user can specialize `SignaturOf` for other types (like `boost::function`) to gain the same support level.
Note that this PR comes from #2319.

Add support for std::function in MockFunction (#2277)

---

googletest/docs/advanced.md

It's merely a proposition for documentation update and doesn't solve the issue #1146, though you might find it useful.

Add documentation for the premature-exit-file protocol

---

googletest/test/googletest-death-test_ex_test.cc

Fixes a `-Wdeprecated` warning.
/home/travis/build/Quuxplusone/googletest/googletest/test/googletest-death-test_ex_test.cc:62:28: error:
dynamic exception specifications are deprecated [-Werror,-Wdeprecated]
const char* what() const throw() override { return "exceptional message"; }
^~~~~~~
/home/travis/build/Quuxplusone/googletest/googletest/test/googletest-death-test_ex_test.cc:62:28: note:
use 'noexcept' instead
const char* what() const throw() override { return "exceptional message"; }
^~~~~~~
noexcept
@zhangxy988 PTAL

Replace the last instance of `throw()` with `noexcept`. NFC.

---

.travis.yml
ci/travis.sh

The old code was trying to pass -Wgnu-zero-variadic-macro-arguments
as part of CXXFLAGS, but it forgot the quotation marks needed around
whitespace. This meant that option was ignored:
https://travis-ci.org/github/google/googletest/jobs/666534177#L760
Unfortunately, the codebase is not remotely clean with respect to that
warning option. It fails like this:
https://travis-ci.org/github/Quuxplusone/googletest/jobs/668118135
So, remove that failing configuration from the test matrix until
someone has time to look at it.

Fix a typo in .travis.yml

---

googlemock/cmake/gmock.pc.in
googlemock/cmake/gmock_main.pc.in
googletest/cmake/gtest_main.pc.in

Google Test and Google Mock require matching versions to work,
so this requirement should be described in the pkgconfig files.
This change is derived from the one used for the Fedora gtest package.
Signed-off-by: Neal Gompa <ngompa13@gmail.com>

Ensure that gtest/gmock pkgconfig requirements specify version

---

googletest/src/gtest-port.cc

This fixes the following error I got when compiling on OpenBSD (with gcc 8.3.0)
```
In file included from /home/jbohl/dev/buildlibCZI/_deps/googletest-src/googletest/src/gtest-all.cc:45:
/home/jbohl/dev/buildlibCZI/_deps/googletest-src/googletest/src/gtest-port.cc: In function 'size_t testing::internal::GetThreadCount()':
/home/jbohl/dev/buildlibCZI/_deps/googletest-src/googletest/src/gtest-port.cc:210:21: error: comparison of integer expressions of different signedness: 'int' and 'size_t' {aka 'long unsigned int'} [-Werror=sign-compare]
for (int i = 0; i < size / mib[4]; i++) {
~~^~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```

fix signed/unsigned comparison issue (on OpenBSD)

---

googletest/test/gtest-unittest-api_test.cc

I like to put this small commit into a separate pull request.
There's a warning during the compilation with the clang compiler (using CMake):
```
~/dev/googletest/googletest/test/gtest-unittest-api_test.cc:59:17: error: implicit conversion changes signedness: 'int' to 'unsigned long' [-Werror,-Wsign-conversion]
unit_test.total_test_suite_count()];
~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
~/dev/googletest/googletest/test/gtest-unittest-api_test.cc:87:19: error: implicit conversion changes signedness: 'int' to 'unsigned long' [-Werror,-Wsign-conversion]
test_suite->total_test_count()];
~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
2 errors generated.
```
Build Environment: 
`clang version 9.0.0-2~ubuntu18.04.2 (tags/RELEASE_900/final)`
`cmake version 3.15.3`

gtest-unittest-api_test - fix warning (clang)

---

ci/travis.sh

Remove the duplicate code in travis.sh, which already exists in get-nprocessors.sh.

Remove duplicate codes existed in get-nprocessors.sh

---

.travis.yml
googlemock/include/gmock/gmock-actions.h
googlemock/include/gmock/gmock-generated-actions.h
googlemock/include/gmock/gmock-generated-actions.h.pump
googlemock/include/gmock/gmock-matchers.h
googlemock/include/gmock/gmock-spec-builders.h
googlemock/src/gmock-matchers.cc
googlemock/test/gmock-actions_test.cc
googlemock/test/gmock-matchers_test.cc
googletest/include/gtest/internal/gtest-internal.h
googletest/include/gtest/internal/gtest-port.h
googletest/test/googletest-param-test-test.cc
googletest/test/googletest-port-test.cc

This is the spiritual successor to #2774 (which I tried and failed to reopen) and #2758.
Fixes #1305.
Remove all uses of `GTEST_DISALLOW_{MOVE_,}ASSIGN_`.
None of these are strictly needed for correctness.
A large number of them (maybe all of them?) trigger `-Wdeprecated`
warnings on Clang trunk as soon as you try to use the implicitly
defaulted (but deprecated) copy constructor of a class that has
deleted its copy assignment operator.
By declaring a deleted copy assignment operator, the old code
also caused the move constructor and move assignment operator
to be non-declared. This means that the old code never got move
semantics -- "move-construction" would simply call the defaulted
(but deprecated) copy constructor instead. With the new code,
"move-construction" calls the defaulted move …

Fix all -Wdeprecated warnings; eliminate GTEST_DISALLOW_ASSIGN_

---

googletest/docs/advanced.md
googletest/include/gtest/gtest.h
googletest/src/gtest-internal-inl.h
googletest/src/gtest.cc
googletest/test/googletest-env-var-test.py
googletest/test/googletest-env-var-test_.cc
googletest/test/gtest_help_test.py
googletest/test/gtest_unittest.cc

Only prints failures and a total pass count. This is useful for CI logs, which are more useful if they just have the failures instead of 100s or 1000s of lines of "PASSED" and the one failure buried in the middle. 
Fixes #358, which was closed but seems to have a few fans...

Add GTEST_QUIET option

---

googletest/src/gtest.cc

Revert the faulty fix from a9f6c1ed14 - that commit cannot concievably fix the issue it sets out to fix, and breaks cross compilation with mingw from case sensitive file systems (causing issue #2840) - see the individual commit message for more detail.
Instead remove the explicit include of debugapi.h - the documentation for IsDebuggerPresent says that including windows.h is enough, and that header takes care of including whichever header declares IsDebuggerPresent in that particular Windows SDK version. This should hopefully fix #2822 properly.

Revert faulty Windows.h include fix and attempt to fix #2822 properly

---

googletest/src/gtest.cc

Fix the #2777 coloring problem :
The first dash of --gtest_print_time is not colored when you use the --help option.

Fix --gtest_print_time coloring

---

googletest/docs/primer.md

fix a documentation link on "how to customize the printing of the arguments"

fix a link to documentation

---

googletest/src/gtest-filepath.cc

An always false condition was remove from Normalize member function of FilePath and the body of the function which was poorly written, is improved.
Closes #2647

Fix always false condition and clean function body

---

googletest/src/gtest.cc
googletest/test/googletest-json-output-unittest.py
googletest/test/gtest_xml_outfiles_test.py
googletest/test/gtest_xml_output_unittest.py
googletest/test/gtest_xml_output_unittest_.cc
googletest/test/gtest_xml_test_utils.py

This pull request adds two things to the xml output:
- The number of skipped tests inside a suite. (As a property, like the number of failures)
- On skipped tests it also adds a skipped element to the xml.
I followed the JUnit description in https://llg.cubic.org/docs/junit/

Output information about skipped tests in xml output

---

googlemock/CMakeLists.txt
googletest/CMakeLists.txt

When building packaged shared libraries for use, having the version
set makes it so that the soname is set correctly for parallel installation.
This change is derived from the one used for the Fedora gtest package.
Signed-off-by: Neal Gompa <ngompa13@gmail.com>

Set the version for the libraries

---

BUILD.bazel
googletest/include/gtest/gtest-printers.h
googletest/include/gtest/internal/gtest-port.h
googletest/include/gtest/internal/gtest-type-util.h
googletest/test/googletest-printers-test.cc

Rework of rejected #2438 due to [the plan on taking hard dependency on Abseil](https://github.com/google/googletest/pull/2438#issuecomment-534136820). I'm resubmitting because recent commit 6f5fd0d7 seems to suggest abandonment of Abseil incorporation like it was planned half a year ago.

Print C++17 types (any, optional and variant) and absl::any

---

CONTRIBUTING.md

This is a minor change.
In googletest CONTRIBUTING.md file, it is found that the existing issue tracker URL is the same as the project repo URL so In order to save user clicks update the exact URL of the issue tracker.

Updated googletest issue tracker url.

---

googletest/cmake/internal_utils.cmake

Use `target_compile_features` to use c++11 if target_compile_features is available. 
This fix compilation with clang and gcc when c++11 isn't specified by user. Otherwise user need to set `-DCMAKE_CXX_STANDARD=11`.
The fix the issue that have been reopened there: https://github.com/google/googletest/issues/1519
This only fix the issue for user using cmake version that support `target_compile_features`, ie CMake greater than 3.1.
This solution is better than `set(CMAKE_CXX_STANDARD 11)` because in superbuild, it won't override any user `CMAKE_CXX_STANDARD` already set variables.
This c++11 requirement will be propagated to any target that `target_link_libraries` as a minimum requirement and won't downgrade any user c++ standard requirement.
And maybe to test if it work as expected, i …

Set cpp11 compile feature with target_compile_features if available.

---

googletest/src/gtest-port.cc

Building on OpenBSD 6.7 current fails due to implicit numeric
conversions.
OpenBSD clang version 8.0.1 (tags/RELEASE_801/final) (based on LLVM 8.0.1)
Target: amd64-unknown-openbsd6.7
Thread model: posix
InstalledDir: /usr/bin
In file included from /tmp/u/build/_deps/googletest-src/googletest/src/gtest-all.cc:45:
/tmp/u/build/_deps/googletest-src/googletest/src/gtest-port.cc:201:19: error: implicit conversion changes signedness:
'int' to 'unsigned long' [-Werror,-Wsign-conversion]
mib[5] = size / mib[4];
~ ^~~~~~
/tmp/u/build/_deps/googletest-src/googletest/src/gtest-port.cc:211:33: error: implicit conversion changes signedness:
'int' to 'unsigned long' [-Werror,-Wsign-conversion]
for (size_t i = 0; i < size / mib[4]; i++) {
~ ^~~~~~ …

Fix compilation on OpenBSD 6.7

---

googletest/test/googletest-death-test-test.cc

Test MatcherDeathTest.DoesNotBreakBareRegexMatching fails when
googletest uses simple regex instead of posix regex.
This partially fixes #2687

Fix test failing when simple regex is used

---

googletest/include/gtest/internal/gtest-internal.h

Prior to the fix using `TEST_F` will cause clang tidy warnings like
```
/home/jasjuang/sample/unit-test/SampleTest.cpp:23:1: warning: use '= default' to define a trivial default constructor [modernize-use-equals-default]
TEST_F(SampleTest, OnePlusOne)
^
/usr/include/gtest/gtest.h:2369:3: note: expanded from macro 'TEST_F'
GTEST_TEST_(test_fixture, test_name, test_fixture, \
^
/usr/include/gtest/internal/gtest-internal.h:1358:58: note: expanded from macro 'GTEST_TEST_'
GTEST_TEST_CLASS_NAME_(test_suite_name, test_name)() {}                   \
^
```
This PR eliminates this warning.

fix clang tidy modernize-use-equals-default warnings

---

googletest/include/gtest/internal/gtest-internal.h
googletest/src/gtest.cc
googletest/test/googletest-shuffle-test_.cc
googletest/test/gtest-typed-test_test.cc
googletest/test/gtest_unittest.cc

I confirmed the following
```
mkdir mybuild
cd mybuild
cmake -Dgtest_build_tests=ON -Dgmock_build_tests=ON -DCMAKE_CXX_FLAGS=-DGTEST_REMOVE_LEGACY_TEST_CASEAPI_ ${GTEST_REPO_DIR}
make && make test
```

fix GTEST_REMOVE_LEGACY_TEST_CASEAPI_ build/test errors

---

README.md

The tiny-dnn project is not using googletest anymore, for more details see (https://github.com/tiny-dnn/tiny-dnn/commit/d0d35ca2f4e75b3f647787e19ee7f31d0784b398).
Removing it from the "Who is Using Google Test?" list so as to keep it accurate.

Removing tiny-dnn from "Who is using.."

---

googlemock/include/gmock/gmock-matchers.h
googlemock/test/gmock-matchers_test.cc

This PR adds matchers that accept a callable and verify that when invoked, it throws an exception with the given type and properties.
Fixes #952

Add matchers for testing exception properties

---

BUILD.bazel

This makes it easier to include the license in redistributions, as required by the license.

Export LICENSE

---

googletest/src/gtest-death-test.cc

This is a resubmission of https://github.com/google/googletest/pull/1590.
WebKit passes -Wl,--no-undefined to the compiler when linking shared
libraries. This is usually a good practice, but it causes gtest to fail
to link because of the use of environ. FreeBSD puts environ symbol in
crt1.o instead of libc.so, so the linker is unable to find environ when
linking a shared library.
Fortunately, there is an easy way to fix it. Since the only use of
environ in gtest is to pass it to execve, we can simply replace execve
with execv to avoid the need of environ. execv is usually a simple
wrapper around execve, so it should be safe to use.
This problem was found and reported more than three years ago. The same
fix is already committed to WebKit and we don't see any problem reports
caused by the …

Avoid using environ on FreeBSD

---

googlemock/docs/cook_book.md

I am working in a project with an older gMock version and was confused that the new way didn't work. Adding a hint when it was added can go a long way :)

Add timestamp to in old method mock macro guide

---

googlemock/include/gmock/gmock-nice-strict.h

#2154
Done as part of hacktoberfest! :)

Issue 2135: Change template args in NiceMock, NaggyMock and StrictMock from A1, A2, ... to TArg1, TArg2,... to avoid clash with legacy header files

---

googletest/src/gtest-filepath.cc

The old algorithm allocates memory for normalization but we can do it in-place

Improve FilePath::Normalize method

---

googletest/docs/advanced.md

See https://github.com/google/googletest/issues/3083 for context. This PR adds specific instructions for how to trigger test failures when sanitizers including UBSan, ASan, and TSan report errors.

Add instructions for sanitizer integration

---

googletest/include/gtest/gtest-printers.h

Detection of string_view type (whether it's std or Abseil) is done in googletest/include/gtest/internal/gtest-port.h with GTEST_INTERNAL_HAS_STRING_VIEW.

Remove a duplicated include

---

README.md
googlemock/README.md
googletest/README.md

This patch updates the tutorial which can be confusing for users
This issue has been raised by the users from
https://github.com/google/googletest/issues/2950
I tried minimize the revision because I don't know exactly what the previous writer intended
and so almost all of the original contents have been preserved

Improve the tutorial that may be confusing

---

googletest/src/gtest-internal-inl.h

On a diskless system you cannot get the current directory. So if
death tests are disabled anyway, there is no point trying to
get current directory.
Without this fix, running tests on diskless systems will fail,
even when death tests are disabled.
Solves https://github.com/google/googletest/issues/3089

Only save original working directory if death tests are enabled

---

googletest/src/gtest.cc

Signed-off-by: Vinson Lee <vlee@freedesktop.org>

Initialize TestInfo member is_in_another_shard_ in constructor.

---

googletest/cmake/internal_utils.cmake

Use `find_package(Python ..)` if available, instead of the deprecated
`find_package(PythonInterp)` CMake module.

Refactor finding python

---

CMakeLists.txt
CONTRIBUTING.md
googlemock/CMakeLists.txt
googletest/CMakeLists.txt
googletest/README.md

Bump CMake minimum to 2.8.12

---

googletest/src/gtest.cc

This fixes build issues with GoogleTest when built with -Wformat-nonliteral and unblocks updating GoogleTest in BoringSSL.
It was added in 53c478d639b8eebd2942e88266610ebc79c541f6, which caught some bugs. Then it was moved to the header and accidentally dropped in 482ac6ee63429af2aa9c44f4e6427873fb68fb1f.

Restore GTEST_ATTRIBUTE_PRINTF_ on ColoredPrintf

---

googletest/include/gtest/gtest.h
googletest/src/gtest.cc

Affects macros {ASSERT|EXPECT}_{EQ|NE|LE|LT|GE|GT}.
According to removed comments, these overloads were supposed to reduce code bloat and allow anonymous enums on GCC 4.
However, the way it works on GCC 4 and the latest GCC (10.2 by now) is that having:
```c++
template <typename T1, typename T2>
void foo(T1, T2);
using BiggestInt = long long;
void foo(BiggestInt, BiggestInt);
```
the template version takes precedence for almost every combination of integral types except for two long long integers - i.e. implicit promotion to long long is a worse match than generating a specific template function.
Tested on [GCC 4.8.1](https://ftp.gnu.org/gnu/gcc/gcc-4.8.1/) (as GoogleTest requires C++11 and this was [the first C++11 feature-complete release of …

Remove explicit function overloads of CmpHelper?? for BiggestInt arguments

---

README.md

Markdown file was moved to a different directory. When googling for
"gtest primer", the result is 404 page.

Fix link to Google Test Primer

---

googlemock/scripts/generator/cpp/gmock_class.py
googlemock/scripts/generator/cpp/gmock_class_test.py

If a function that takes no arguments explicitly states (void)
then do not include it in the mocked method argument list
since it triggers static assertions that expect no arguments
to be present.
Fixes #3261

[gmock_gen.py] Do not include void into mocked method arguments

---

googletest/cmake/internal_utils.cmake

This is incompatible with compiler caches such as sccache and
clcache. If a project including Google Test specifies /Z7 instead,
building fails with:
```
sccache C:\PROGRA~2\MICROS~1\2019\ENTERP~1\VC\Tools\MSVC\1428~1.293\bin\Hostx64\x64\cl.exe  /nologo /TP -D__SSE2__ -D__SSE__ -I..\lib\googletest-1.10.x\googlemock\include -I..\lib\googletest-1.10.x\googlemock -I..\lib\googletest-1.10.x\googletest\include -I..\lib\googletest-1.10.x\googletest /DWIN32 /D_WINDOWS /W4 /GR  /MD /Z7 /O2 /Ob1 /DNDEBUG -GS -W4 -WX -wd4251 -wd4275 -nologo -J -Zi -D_UNICODE -DUNICODE -DWIN32 -D_WIN32 -DSTRICT -DWIN32_LEAN_AND_MEAN -wd4702 -DGTEST_HAS_PTHREAD=0 -EHsc -D_HAS_EXCEPTIONS=1  /Gy /showIncludes /Folib\googletest-1.10.x\googlemock\CMakeFiles\gmock_main.dir\src\gmock-all.cc.obj /Fdbin\gmock_main.pdb /FS -c …
```

remove -Zi from MSVC compiler options

---

BUILD.bazel

Our projects are using the platforms API and our targets that use googletest were failing to build due to using `@bazel_tools//platforms`.
```
ERROR: C:/users/zekew/_bazel_zekew/5hhwqc6f/external/bazel_tools/platforms/BUILD:79:6: in alias rule @bazel_tools//platforms:windows: Constraints from @bazel_tools//platforms have been removed. Please use constraints from @platforms repository embedded in Bazel, or 
preferably declare dependency on https://github.com/bazelbuild/platforms. See https://github.com/bazelbuild/bazel/issues/8622 for details.
ERROR: While resolving configuration keys for @com_google_googletest//:gtest: Analysis of target '@bazel_tools//platforms:windows' failed
```

Use platforms instead of bazel_tools for windows constraint

---

googletest/CMakeLists.txt
googletest/cmake/internal_utils.cmake

Fixes #3125
I've assumed that #3094 will be in shortly, and so there's no need to guard this like in other places, for example: https://github.com/google/googletest/blob/93748a946684defd1494d5585dbc912e451e83f8/googletest/cmake/internal_utils.cmake#L178
I've also had to make sure `cmake_package_name` is always set so that the namespace is consistent between exported targets and the alias libraries.

CMake: Add namespaced ALIAS library

---

googlemock/include/gmock/gmock-nice-strict.h

An incorrect link is output to the user when these conditions are met.

Update nicestrictnaggy gmock cook_book links

---

googletest/README.md

Hi,
instead of ExternalProject and a new file that is spawned in a new process, it's easier to just use FetchContent. cmake 3.14 should be old enough to be spread.

Use Fetchcontent instead of ExternalProject

---

docs/advanced.md

A subsection "Skipping test execution" was added to document GTEST_SKIP
and where it can be used.
relates issue #1544

Add subsection for GTEST_SKIP documentation

---

googletest/include/gtest/internal/gtest-param-util.h

I spotted this in https://github.com/assimp/assimp/pull/3880/commits/7dd7a053a91322fad88cdf958c6d0b3b7b91cb90 and figured I'd fix it here, too. 
If this is not the right thing to do, please lmk so I can undo it in assimp, too. Seems right, though. It's the only spot in gtest where a ctype call was made directly.

isalnum -> IsAlNum for correct handling of signed chars

---

googlemock/include/gmock/gmock-matchers.h

Hi!
I propose to make a matcher ElementsAreArray applicable for std ranges.
It is small changes in the code but it allow to make assertions of containers easy.
Compilers gcc 5.0, clang 5.0, MSVC 2015 support 'auto' so you don't need to enhance requirements for compilers. And users with modern compillers can use modern features.

Make a matcher ElementsAreArray applicable for std ranges

---

googletest/include/gtest/internal/gtest-death-test-internal.h

EXPECT_DEATH() and ASSERT_DEATH() have a switch case where every
possible case is covered. This makes the default case unnecessary
and triggers -Wcovered-switch-default.
Due to these being macros, the lines are expanded in user code and
are thus subject to warnings of the target codebase.
Fixes #3456

Fix EXPECT_DEATH() and ASSERT_DEATH() triggering -Wcovered-switch-default

---

BUILD.bazel
googlemock/test/BUILD.bazel
googletest/test/BUILD.bazel

On QNX, pthread is part of libc. There's no separate pthread library to link. See section "Library" in the [`pthread_create()`](https://www.qnx.com/developers/docs/7.1/index.html#com.qnx.doc.neutrino.lib_ref/topic/p/pthread_create.html) reference manual of QNX.
Resolves https://github.com/google/googletest/issues/3464

Don't link pthread on QNX

---

BUILD.bazel

According to the 2nd point on [1], `-lregex` is required on QNX. This is a follow-up PR for https://github.com/google/googletest/pull/3465.
[1] https://www.qnx.com/developers/docs/7.1/#com.qnx.doc.ide.userguide/topic/writing_test_programs.html
Relates to https://github.com/google/googletest/pull/3484

Link -lregex on QNX

---

googletest/README.md
googletest/include/gtest/gtest.h

The [documentation](https://github.com/google/googletest/blob/release-1.11.0/googletest/README.md#avoiding-macro-name-clashes) is clear that the FOO we'll be guarding always matches
the spelling of the DONT macro.  A single guard macro should not toggle
more than one implementation macro.
This fixes a regression in 7413280c52c1f759395572a384165023d24eeb57.
Relatedly, improve the documentation of the DONT macros to bring the
list of valid FOO values up to date.

Use GTEST_DONT_DEFINE_TEST_F to guard TEST_F

---

googlemock/include/gmock/gmock-matchers.h
googlemock/include/gmock/gmock-spec-builders.h
googlemock/test/gmock-actions_test.cc
googletest/src/gtest-death-test.cc
googletest/src/gtest.cc
googletest/test/gtest_unittest.cc

fix code spell ```googletest```

fix: typo codespelling comment

---

docs/gmock_cook_book.md

This commit fix unnecessary space at gMock Cookbook docs

typo fix gmock_cook_book

---

BUILD.bazel
WORKSPACE
docs/quickstart-bazel.md
googlemock/test/BUILD.bazel
googletest/test/BUILD.bazel

bazelbuild/rules_cc was put on hold
It seems the recommended way is now to use native cc rules
More info [here](https://github.com/bazelbuild/rules_go/pull/2950)

Remove bazelbuild/rules_cc dependency

---

googlemock/include/gmock/gmock-matchers.h
googletest/src/gtest-internal-inl.h

Using auto instead of container::const_iterator

---

docs/reference/matchers.md
googlemock/include/gmock/gmock-matchers.h
googlemock/include/gmock/gmock-spec-builders.h
googlemock/test/gmock-matchers_test.cc
googletest/include/gtest/internal/gtest-internal.h
googletest/include/gtest/internal/gtest-port.h
googletest/test/gtest_test_utils.py

Finish the effort started in #3573
[`codespell --ignore-words-list=atleast,ba,creat,fo,seh,wan`](https://pypi.org/project/codespell)

Fix remaining typos discovered by codespell

---

googletest/include/gtest/gtest.h
googletest/src/gtest.cc

A new flag is herein created, --gtest_print_disabled_test_names,
whose default value is false (so that by default, the behaviour
will not change).
The functionality is implemented by a new member function on the
TestEventListener interface (which is responsible for printing
testing output) which is called when a disabled test is encountered.
The PrettyUnitTestResultPrinter has the canonical implementation of this
added function. The BriefUnitTestResultPrinter and the
EmptyTestEventListener get a nullary implementation. The
JsonUnitTestResultPrinter and XmlUnitTestResultPrinter
inherit that trivial implementation from the EmptyTestEventListener.

Re #3637 Show Disabled Tests in testing output

---

googletest/src/gtest-port.cc

Added GetLastError() on Windows for CreateThread().
This is in relation to #3629. It does not close the issue but may be very helpful to isolate problems. The change is minimal, and has been copied from another location in the same file, so it should be easy to review.
See for reference
https://github.com/google/googletest/blob/5a93ce124714287ab78c92da6db986be7fdb791c/googletest/src/gtest-port.cc#L460
Thanks for your consideration!

googletest/src/gtest-port.cc: Added GetLastError() on Windows

---

googlemock/test/gmock-matchers_test.cc

This was deprecated by [P0174](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0174r2.html#2.1) in C++17.

Replace use of deprecated std::iterator

---

googletest/src/gtest-port.cc

When `_DEBUG` is not defined the `_CrtSetDbgFlag` turns into `((int)0)`, which causes clang to issue a warning `Wunused-value`.

Suppress unused-value warning

---

.github/workflows/gtest-ci.yml

Running on major platforms.
I'd like to contribute a starting point for a CI that can run on pushes and pull requests, which is in particular useful to make sure that things continue working on all platforms.
Note, the Windows run actually fails right now and it looks like it might actually be worthwhile looking into that. One test looks like a CR to CRLF mismatch. And there is some death test message that doesn't fit. I'll leave that to the googletest team to work out.

Start a simple github actions CI

---

docs/primer.md

Example contains
```bash
q1_
q2_
q2_
```
whereas it should be 
```bash
q0_
q1_
q2_
```

Typo in the queue test of the README

---

googletest/CMakeLists.txt

Similar to https://github.com/google/googletest/pull/3484 but when building with cmake. QNX requires linking against regex

Link gtest to regex on QNX systems

---

googlemock/include/gmock/gmock-matchers.h

They were all removed in #2815, but it looks like this one got added
from a Google export which missed the update. See #2815 for reasons why
removing this is desirable.

Remove another GTEST_DISALLOW_ASSIGN_ that crept in

---

googletest/src/gtest.cc

We should perform an explicit type conversion to `unsigned char` before passing the `const char` data to `IsValidXmlCharacter()` and `IsNormalizableWhitespace()` functions in order to avoid compile time conversion warnings.
Fixes #3719 
Signed-off-by: Ayush Joshi <ayush854032@gmail.com>

FIX #3719 -- Fix `clang` conversion warnings

---

googletest/cmake/internal_utils.cmake

While this is not synced with the pkg-config file, it only breaks things
Fix #2174
Signed-off-by: Ayush Joshi <ayush854032@gmail.com>

FIX #2174 -- remove `DEBUG_POSTFIX`

---

CMakeLists.txt

INSTALL_GTEST cannot be set to OFF due to CMake Policy CMP0077 when using FetchContent, for example:
include(FetchContent)
set(INSTALL_GTEST OFF)
FetchContent_Declare(
googletest
GIT_REPOSITORY https://github.com/google/googletest.git
GIT_TAG        release-1.11.0
)
FetchContent_MakeAvailable(googletest)
Setting the policy to new fixes this.

Fix BUILD_GMOCK and INSTALL_GTEST options when using CMake FetchContent

---

googlemock/CMakeLists.txt
googletest/CMakeLists.txt

Replace semicolon by `$<SEMICOLON>` in generator-expressions of target
property `INTERFACE_INCLUDE_DIRECTORIES` of CMake targets `gtest`,
`gtest_main`, `gmock` and `gmock_main`.
Fixes: #3616

CMake: Replace semicolon in genex of INTERFACE_INCLUDE_DIRECTORIES target property by $<SEMICOLON>

---

googletest/src/gtest.cc

We can use O(1) look up for patterns that are exact names of the tests. This issue arose from #3614 but I am not sure if it is something that the maintainers would want in the library.

Do constant time matching for exact match filters.

---

googletest/include/gtest/gtest-matchers.h

This fixes -Wuninitialized warnings with GCC.
Fixes #3514.

Always initialize fields in MatcherBase constructors

---

googletest/test/googletest-filepath-test.cc

Fix typo in the test name of `NormalizeTest`.
Signed-off-by: Ayush Joshi <ayush854032@gmail.com>

Fix typo in the test name of `NormalizeTest`

---

googletest/include/gtest/internal/gtest-port.h
googletest/src/gtest.cc

Currently, there is redundant logic in `ColoredPrintf` where some cases are handled with preprocessor macro to detect embedded devices, and for the other cases, the `IsATTY` test is used.
Instead, this should be simplified such that `IsATTY` is always used, but `IsATTY` relies on preprocessor macros to handle the embedded cases.
This provides a single customization point when controlling if the output should use colours or not by customizing `DoIsATTY` in `gtest-port.h`

Simplify ColoredPrintf to rely on ShouldUseColor

---

googletest/src/gtest.cc

Most compilers won't require static const to have a definition in an object file, but unfortunately some do... This PR fixes the following error in clang:
```
error : undefined symbol: testing::internal::Random::kMaxRange
```

Fix for undefined symbol: testing::internal::Random::kMaxRange

---

docs/quickstart-cmake.md

CMake_FetchContent provides a popular way to make it easy to compile a package, by allowing CMake to fetch and compile the package's dependencies during the build process.
However, the instructions provided for using GoogleTest with CMake_FetchContent have issues that make it incompatible with usage of GoogleTest with find_package.
This issue occurs in the way users are instructed to link against GoogleTest:
```cmake
target_link_libraries(
hello_test
gtest_main
)
```
When GoogleTest is used with CMake_FetchContent, this will link against `GTest::gtest_main`, which is a CMake library target that causes `hello_test` to be linked against *both* `libgtest_main.so` as well as `libgtest.so`.
However, if a user instead uses GoogleTest via `find_package`, linking against `gtest_main` is now …

Fix quickstart-cmake documentation

---

googlemock/src/gmock-internal-utils.cc
googletest/include/gtest/internal/gtest-internal.h
googletest/src/gtest.cc
googletest/test/googletest-param-test-test.cc
googletest/test/gtest-unittest-api_test.cc
googletest/test/gtest_unittest.cc

Changes:
1. Unused parameter was removed from `::testing::internal::GetCurrentOsStackTraceExceptTop`. This code was reworked more than a decade ago aaebfcdc4005afb22b68df61b58edd1ccc002913.
2. In a couple of tests return type was replaced with `const auto&`. It's a little bit more convenient because uncouples the implementation of the tests from the return type of `::GetInstance()`.
```
make test
Running tests...
...
100% tests passed, 0 tests failed out of 63
Total Test time (real) =   7.67 sec
```

Cleanup of gtest.cc and a couple of unittests

---

googlemock/test/gmock-actions_test.cc
googlemock/test/gmock-matchers-misc_test.cc
googlemock/test/gmock-spec-builders_test.cc
googletest/include/gtest/internal/gtest-internal.h
googletest/src/gtest-internal-inl.h
googletest/src/gtest.cc

This PR fixes various typos in different places.

Fix some typos

---

googletest/cmake/internal_utils.cmake

CMake policy CMP0094 controls a lookup strategy used to find a Python executable:
* CMP0094=OLD selects a Python executable with a higher version.
* CMP0094=NEW selects a Python executable found earlier in PATH.
NEW behavior is critical in presence of a Python virtual environment established and activated, i.e. added to the PATH variable.
In case GoogleTest is embedded into a larger project, the result of `find_package(Python)` affects the whole build, not only GoogleTest component itself.

cmake: find python in order specified by PATH environment variable.

---

googletest/include/gtest/internal/gtest-port.h

export ThreadLocalValueHolderBase which is required by exported APIs.

---

googletest/cmake/internal_utils.cmake

PDB files should be created at the same location as their primary artifact, which is either static library or a DLL.
On Windows, an artifact location is controlled by:
* RUNTIME_OUTPUT_DIRECTORY is a directory of a DLL artifact.
* ARCHIVE_OUTPUT_DIRECTORY is a directory of a LIB artifact.
A PDB file location is controlled:
* PDB_OUTPUT_DIRECTORY should match a directory of a DLL artifact.
* COMPILE_PDB_OUTPUT_DIRECTORY should match a directory of a LIB artifact.

cmake: make PDB output directory match that of a static library.

---

googletest/include/gtest/gtest-printers.h

Some of the #ifdefs were missed in original PR #3183.
Should be fixed now.

Continuation for #3183

---

googletest/src/gtest-death-test.cc

gtest-death-test: add 'noreturn'

---

.bazelrc
.github/workflows/gtest-ci.yml
ci/linux-presubmit.sh
ci/macos-presubmit.sh

Bazel defaults to -std=c++11 on macOS which gtest doesn't support.

bazel: move -std=c++14 to .bazelrc

---

googlemock/src/gmock-spec-builders.cc
googletest/include/gtest/internal/gtest-port-arch.h
googletest/include/gtest/internal/gtest-port.h
googletest/src/gtest-filepath.cc
googletest/src/gtest_main.cc

This change makes possible to build and use Google Test framework on Hexagon DSPs

Port GoogleTest to QuRT (Hexagon RTOS)

---

googletest/src/gtest.cc

#3884
`diff new-googletest-output-test_result old-googletest-output-test_result`
```
1886,1887c1886
<     },
<     {
---
>     }    {
```

Fix JSON output format

---

googletest/README.md

gnu domain doesn't force the ssl redirection.

fixing gcc.gnu domain redirection

---

googletest/src/gtest.cc

The error occurs if `!GTEST_HAS_DEATH_TEST` on Windows.
I could not make the change better. If I make
```c++
bool in_death_test_child_process = false;
#if GTEST_HAS_DEATH_TEST
in_death_test_child_process =
GTEST_FLAG_GET(internal_run_death_test).length() > 0;
```
then the error about an assigned but unused variable occurs on Linux.

Fix error in_death_test_child_process: undeclared identifier

---

googletest/include/gtest/internal/gtest-port.h

Environment variables, for example `GTEST_FILTER`, `GTEST_OUTPUT` can be set before getting WinRT app run. GoogleTest can read environment variables and use them. It's easier than setting and passing command line parameters to WinRT app.

Environment variables are accessible in UWP/WinRT apps

---

googletest/include/gtest/gtest-printers.h
googletest/src/gtest-printers.cc
googletest/test/googletest-printers-test.cc

In MSVS `std::u8string` is enabled only when `__cpp_lib_char8_t` is defined. `__cpp_char8_t` enables only `char8_t`. This PR complements aa2e91fd6918519dafa3bee4aa706d04857e7d06 and 996328bb8eeea7e3b824a7cf4c156640600d9778.
More details:
https://developercommunity.visualstudio.com/t/support-for-cpp-char8-t-feature-test-macro-and-if/586040
https://en.cppreference.com/w/cpp/feature_test
In MSVS, when compiled with pre-c++20 compiler, char8_t is enabled with `/Zc:char8_t` flag. But this flag does not enable library support, which in MSVS comes only with c++20. It's quite easy to reproduce
```
PS C:\w\thirdparty\googletest\mybuild> git diff
diff --git a/googletest/cmake/internal_utils.cmake b/googletest/cmake/internal_utils.cmake
index 0438bef8..502f09f4 100644
--- …
```

__cpp_char8_t does not cover std::u8string implementation

---

googletest/cmake/internal_utils.cmake

When googletest and googlemock are included as a git submodule and referenced as part of an existing CMake project, multiple warnings are printed out due to not setting a value for the CMP0069 policy.

Set CMP0069 policy to avoid warnings

---

googletest/include/gtest/internal/gtest-port.h

Closes #3849.
I've submitted a CLA.

Fix warnings with nvc++ as the compiler

---

googlemock/test/gmock-spec-builders_test.cc

Rename 'Result' struct to 'NonMoveableStruct' in
gmock-spec-builders_test.cc in ExpectCallTest.NonMoveableType test
I prepared new change and closed old PR #4221  because in old one I meesed with commit history so sorry about that @dinord originaly was assigned to PR #4221

gmock: fix issue #4222

---

googletest/src/gtest-death-test.cc
googletest/src/gtest-internal-inl.h
googletest/test/googletest-filepath-test.cc
googletest/test/gtest_xml_test_utils.py

Fix spelling

---

BUILD.bazel

https://github.com/google/googletest/commit/dea0484e4d3b6a2c50055c24c5617cd662a50c5f added an include on `absl::flat_hash_set` but didn't update the build. So it fails to build if we don't have the correct transient include.

Add missing absl dependency from build.

---

docs/quickstart-cmake.md
googletest/README.md

The `CXX_STANDARD` property specifies the language standard that the project wants to use if it is available. `CXX_STANDARD_REQUIRED` makes it a hard requirement. Note that `CXX_STANDARD_REQUIRED` is turned off by default.

Add CXX_STANDARD_REQUIRED to CMake quickstart

---

googletest/src/gtest-internal-inl.h

Check for current directory instead of death test to get original directory.
A port may support filesystems but not death tests.

Check for file system for current directory

---

.gitignore

This is populated by the clangd language service provider.
Also ignore the cmake-variants.yaml file.
This can be created locally to select various build/test configurations.
Fixes #4266

Ignore the .cache directory created by VSCode.

---

CMakeLists.txt
docs/pkgconfig.md
googlemock/CMakeLists.txt
googletest/CMakeLists.txt

From the CMake 3.27 release notes:
Compatibility with versions of CMake older than 3.5 is now deprecated and will be removed from a future version. Calls to cmake_minimum_required() or cmake_policy() that set the policy version to an older value now issue a deprecation diagnostic.
This PR also removes manually setting policy CMP0048. This is redundant since the CMake min is already 3.X

cmake: Raise min to 3.6

---

CMakeLists.txt
googletest/CMakeLists.txt
googletest/cmake/internal_utils.cmake

Now that the min is 3.13 these policies don't need to be set manually anymore.
CMP0054 - 3.1
CMP0063 - 3.3
CMP0069 - 3.9
CMP0077 - 3.13

cmake: Clean up policy code

---

googlemock/CMakeLists.txt
googletest/CMakeLists.txt
googletest/cmake/internal_utils.cmake

Remove conditional code that doesn't need to exist anymore.

cmake: Remove remaining checks for CMAKE_VERSION

---

googletest/include/gtest/internal/gtest-port-arch.h
googletest/include/gtest/internal/gtest-port.h
googletest/src/gtest-filepath.cc

Added additional defines to correctly detect the NXP QN9090 MCU platform and allow for native googletest compability.

Add support for the NXP QN9090 MCU

---

googlemock/include/gmock/gmock-actions.h

When a mocked function returns a custom type without a default constructor, MSVC will trigger a C4702 warning.
This PR takes the same approach as is done in [`Invalid<T>()`](https://github.com/google/googletest/blob/main/googlemock/include/gmock/internal/gmock-internal-utils.h#L316) to avoid the warning.

Avoid unreachable code warning

---

googletest/include/gtest/gtest.h
googletest/include/gtest/internal/gtest-internal.h

This commit removes `<iomanip>` from public GoogleTest header files.
As `<iomanip>` is not a common included file, its content is unlikely to be included in translation units other than through GoogleTest includes.
By reducing the number of include directives public headers in GoogleTest, this may reduce the time taken to compile tests as it would reduce the amount of work that the preprocessor and compiler front-end need to do.

Remove public includes of `<iomanip>`

---

googletest/test/googletest-port-test.cc

The last regular expression specified in the test is not technically POSIX compatible. Use `[[:alnum:]_]` instead of `\w+`; the latter is a Perl-compatible regular expression.

Fix RETest/1.ImplicitConstructorWorks on non-ABSL platforms

---

googletest/test/gtest_help_test.py

The test supported a variety of BSDs, including kFreeBSD, but not FreeBSD.
Move the BSD checks to a separate function and support checking for FreeBSD, in addition to kFreeBSD.

Fix GTestHelpTest.TestHelpFlag on FreeBSD

---

googletest/src/gtest.cc

Adds support for kDefault option and also prevents from returning nullptr by choosing default color.
Issue: #4321

googletest: ansi color

---

CONTRIBUTING.md
README.md
docs/advanced.md
docs/faq.md

Changed unencrypted public links to use HTTPS.
The new URLs work well.
I've signed the Contributor License Agreement

Http to https, issue number #4341

---

googletest/test/googletest-port-test.cc

The `Mutex` is locked with the `MutexLock` before spawning the thread, so that the thread is prevented from completing (by being blocked on `Mutex`) before the new thread count is obtained. However, the existing bug (introduced in 22e6055) releases `Mutex` before obtaining the new thread count, which allows the thread to run to completion in the meantime.
Also, since the `(thread_count_after_create != starting_count + 1)` condition (line 328) skips the remainder of the `for`-loop body on every iteration, `thread_count_after_join` stays uninitialized.
I believe this is why [this test failed][1] on the macOS CI with this trace:
```
[----------] 1 test from GetThreadCountTest
[ RUN      ] GetThreadCountTest.ReturnsCorrectValue
googletest/test/googletest-port-test.cc:350: Failure
Expected …
```

Count threads after thread-creation while still holding mutex lock

---

googletest/src/gtest-port.cc

Newer devices can have the latter location read-only. (I observed this with Termux on a non-rooted Pixel 6.)
Fixes: #4167

Prefer $TMPDIR to /data/local/tmp on Android

---

googlemock/include/gmock/gmock-function-mocker.h

This fixes compile warning `conversion to ‘long unsigned int’ from ‘int’ may change the sign of the result` in gmock-function-mocker.h.
Template type int changed to size_t.

Fix compile warnings in gmock-function-mocker.h

---

CMakeLists.txt
googlemock/CMakeLists.txt
googletest/CMakeLists.txt
googletest/cmake/internal_utils.cmake

Remove extra spaces. Fix so that the comment line starts with a capital letter and ends with a dot.

cmake: Fix comments in cmake files

---

googletest/src/gtest.cc

If SIGTRAP is defined, this file may end up using raise(3), which is defined in csignal, leading to a compilation failure on at least OpenBSD/sparc64 with gcc 8.

Add missing include for raise(3)

---

googletest/CMakeLists.txt

In QNX versions prior to 7.1, the regex functionality was located in `libc.a` and no extra linker flag was required. In QNX 7.1 and newer, we do need to link against the new `libregex`, which is what the current approach does always, breaking builds against older QNX versions.
Add check of `CMAKE_SYSTEM_VERSION` to handle this. QNX 7.0 is admittedly long in the tooth but it would be nice to keep this in good shape until it's commercially EOL'd in 2027.

Only apply -lregex for qnx710 and newer

---

googletest/src/gtest-death-test.cc

Fixed gcc linker error 58:
How to reproduce:
Step1. Build the library with a test project deployed on gcc 12.3 on Ubuntu
Step2. Look at the following linker error:
```
lto-wrapper : warning : using serial compilation of 8 LTRANS jobs
lto-wrapper : message : see the ‘-flto’ option documentation for more information
lto-wrapper : message : In function ‘make_unique’,
E: from ‘CreateArgvFromArgs’ at \mnt\d\Code\utilities\submodules\googletest\googletest\src\gtest-death-test.cc(635): error : 58,
E: from ‘AssumeRole’ at \mnt\d\Code\utilities\submodules\googletest\googletest\src\gtest-death-test.cc(1391): error : 58:
/usr/include/c++/12/bits/unique_ptr.h(1080): error : 30: warning: argument 1 value ‘18446744073709551615’ exceeds maximum object size 9223372036854775807 [-Walloc-size-larger-than=] …
```

Fixed gcc linker error 58

---

googletest/src/gtest.cc

Support for Mac was previously added, in addition to Linux. Fix the help text to match the code.

Fix help text for stream_result_to flag.

---

googletest/include/gtest/internal/gtest-port.h

This fixes the following issue https://github.com/google/googletest/issues/4526 by adding z/OS to support death tests.

Add zos for death test support

---

MODULE.bazel
ci/windows-presubmit.bat

since it affects downstream users
The correct solution appears to be
https://rules-python.readthedocs.io/en/stable/toolchains.html#library-modules-with-dev-only-python-usage
This change also includes a workaround for the new mechanism creating paths that are too long for Windows to handle.
Backport of 3e3b44c300b21eb996a2957782421bc0f157af18

Remove auto-detection of Python toolchain from MODULE.bazel

---

googletest/include/gtest/gtest-matchers.h

Matchers require the signature of these three functions to be `const`.

Fix documentation bug.

---

googlemock/test/gmock-actions_test.cc

This pull request fixes a build error encountered when compiling GoogleMock tests with GCC 12 on the Steam Runtime (SteamRT) distribution.
The error was caused by an extra semicolon (;) following a member function definition, which triggers `-Wextra-semi ` warnings treated as errors under stricter compiler settings.

Fix build error with GCC 12: Remove extra semicolon after member function definition
