googlemock/configure.ac
googlemock/scripts/fuse_gmock_files.py
googlemock/test/gmock_test.cc

Fix the googlemock autotools build.

---

googlemock/README.md

Fix relative links in googlemock docs.

---

googletest/README.md

update googletest readme to fix broken links

---

googletest/CMakeLists.txt
googletest/include/gtest/internal/gtest-port.h
googletest/src/gtest-internal-inl.h

This fixes [#451]. I've signed the CLA.

Fix building of gtest with -fvisibility=hidden [#451]

---

googletest/docs/AdvancedGuide.md

Some tables have missing commas inside the code that make some table cells merge, added missing commas

Fixing some table error in file

---

googletest/docs/FAQ.md

(FYI I'm a Googler - tansell@google.com, see http://go/github)

Fix AdvancedGuide link in FAQ.md

---

googletest/src/gtest.cc
googletest/test/gtest_unittest.cc

Add tmux and tmux-256color to the colored terminal list.

---

googletest/scripts/fuse_gtest_files.py
googletest/test/gtest_env_var_test.py
googletest/test/gtest_filter_unittest.py
googletest/test/gtest_output_test.py
googletest/test/gtest_test_utils.py
googletest/test/gtest_throw_on_failure_test.py
googletest/test/gtest_uninitialized_test.py
googletest/test/gtest_xml_output_unittest.py
googletest/test/gtest_xml_test_utils.py

Adds support for running googletests own tests and the 'fuse' script with python 3. Fixes #434

Python 3 support

---

.gitignore
googletest/.gitignore

A minor bit of cleanup to ignore artifacts generated by the CI build but that should not be tracked by git.

Add build artifacts to git ignore.

---

googlemock/make/Makefile
googlemock/msvc/2005/gmock_config.vsprops
googlemock/msvc/2010/gmock_config.props
googlemock/msvc/2015/gmock.sln
googlemock/msvc/2015/gmock.vcxproj
googlemock/msvc/2015/gmock_config.props
googlemock/msvc/2015/gmock_main.vcxproj
googlemock/msvc/2015/gmock_test.vcxproj

Updated vs props and makefiles of googlemock to reflect the new location of googletest.
Please refer to issue #772

Fixed googletest dir issue for building googlemock.

---

CMakeLists.txt
googlemock/CMakeLists.txt
googletest/CMakeLists.txt

2.6.4 is the minimum CMake version, so enforce it

---

googlemock/README.md

Address dead links reported in Issue #1028

Remove /tree/ from Readme.md links.

---

googletest/include/gtest/gtest.h
googletest/include/gtest/internal/gtest-port.h
googletest/src/gtest-port.cc
googletest/src/gtest.cc
googletest/test/gtest_unittest.cc

Changes to make TempDir() public

---

googletest/include/gtest/gtest.h

This merges a Google-internal change.

Gender-neutralize comments in gtest.h.

---

googlemock/docs/ForDummies.md

docs: fix broken link

---

googlemock/docs/CookBook.md
googlemock/docs/v1_5/CookBook.md
googlemock/docs/v1_6/CookBook.md
googlemock/docs/v1_7/CookBook.md

The markdown was not working for a small table, fixed.

Fix table formatting.

---

googletest/docs/AdvancedGuide.md

I think this makes the docs better "surfable"

added link to sample 6 in the  documentation of typed test

---

googlemock/CHANGES
googlemock/src/gmock-matchers.cc
googlemock/test/gmock-generated-actions_test.cc
googletest/docs/AdvancedGuide.md
googletest/docs/V1_5_AdvancedGuide.md
googletest/docs/V1_6_AdvancedGuide.md
googletest/docs/V1_7_AdvancedGuide.md
googletest/src/gtest-death-test.cc
googletest/src/gtest-port.cc
googletest/src/gtest.cc
googletest/test/gtest_unittest.cc
googletest/xcode/Scripts/versiongenerate.py

Signed-off-by: Li Peng lip@dtdream.com

remove duplicated words

---

CMakeLists.txt

Fix policy issue with old cmakes

---

CMakeLists.txt

Fixes issue #1171 by changing policy argument to uppercase.

Fix cmake policy issue

---

googletest/samples/sample3_unittest.cc

jumbled letters in comment only :-)

fix small typo in comment

---

README.md

tiny-dnn in its recent version updated the testing framework to GTest
https://github.com/tiny-dnn/tiny-dnn/pull/361
We would like to be mentioned as consumers of the project.

update README.md with tiny-dnn

---

googlemock/include/gmock/gmock-actions.h

This upstreams a Google-internal change (141765019).

Fix typo in gmock-actions.h

---

googletest/docs/AdvancedGuide.md

Fix punctuation in docs

---

README.md
googlemock/README.md
googletest/docs/FAQ.md
googletest/docs/Primer.md
googletest/docs/PumpManual.md
googletest/docs/XcodeGuide.md

Typos, punctuation & broken links

Minor style fixes

---

googlemock/src/gmock-spec-builders.cc
googlemock/test/gmock-nice-strict_test.cc

Second try. I hope it works this time...You aren't making it easy to contribute to Google projects. 😞

Add function name to exception if there's no default action

---

googlemock/include/gmock/gmock-matchers.h
googlemock/test/gmock-matchers_test.cc

This PR is up-streaming an internal change (cl/164723790).

Support ref-qualified member functions in Property().

---

googlemock/docs/CookBook.md

Small fixes for typos mentioned in #1105.

fix typos mentioned in issue 1105

---

googletest/docs/AdvancedGuide.md

fix SetUp/TearDownTestCase() in AdvancedGuide

---

.travis.yml

Reverts google/googletest#1297

Revert "Workaround for Travis issue https://github.com/travis-ci/travis-ci/is…"

---

.travis.yml

Workaround for Travis issue https://goo.gl/d5eV8o

---

googletest/test/gtest-death-test_test.cc
googletest/test/gtest-filepath_test.cc
googletest/test/gtest-options_test.cc
googletest/test/gtest-param-test2_test.cc
googletest/test/gtest-port_test.cc
googletest/test/gtest_break_on_failure_unittest_.cc
googletest/test/gtest_output_test_.cc
googletest/test/gtest_repeat_test.cc
googletest/test/gtest_stress_test.cc
googletest/test/gtest_xml_outfile1_test_.cc
googletest/test/gtest_xml_outfile2_test_.cc
googletest/test/gtest_xml_output_unittest_.cc

code cleanup in preparation for merges, cl 180857299

---

googlemock/docs/CookBook.md
googlemock/include/gmock/gmock-matchers.h
googlemock/scripts/generator/cpp/ast.py
googlemock/test/gmock-actions_test.cc
googlemock/test/gmock-matchers_test.cc
googletest/docs/FAQ.md
googletest/include/gtest/internal/gtest-filepath.h
googletest/src/gtest-filepath.cc
googletest/src/gtest-printers.cc
googletest/src/gtest.cc
googletest/test/gtest-printers_test.cc
googletest/test/gtest_test_utils.py
googletest/test/gtest_unittest.cc
googletest/xcode/Scripts/versiongenerate.py

Fixed typos

---

googletest/include/gtest/internal/gtest-port.h

Reverts google/googletest#1525

Revert "merging gtest-port, 2"

---

googletest/include/gtest/internal/gtest-port.h

Reverts google/googletest#1518

Revert "merging gtest-port 1 of N"

---

googletest/include/gtest/internal/gtest-internal.h

fix build break on locale windows

fix build break on locale windows

---

googletest/test/gtest-port_test.cc

Upstream cl 191754725

---

.travis.yml
ci/travis.sh

(I'm not sure if this is right yet, I'm hoping creating a pull request will run a Travis build?)

Add no-exception and no-rtti to build matrix

---

googletest/include/gtest/gtest-printers.h
googletest/test/gtest-printers_test.cc

Add printer for std::nullptr_t, 
Addressing #1616 
Upstream, cl/199129756

Adress, #1616, add  printer for std::nullptr_t

---

googlemock/test/gmock_ex_test.cc

Fix issue #1654.
Signed-off-by: Adrian Moran <amoran@ikerlan.es>

Fix issue #1654.

---

googletest/docs/primer.md

Fixing some formatting in docs/primer

---

googletest/src/gtest-death-test.cc

https://github.com/google/googletest/issues/1711#issuecomment-411788837

 Fixing identation, causes build errors when warnings are treated as errors

---

googletest/include/gtest/internal/gtest-port.h
googletest/src/gtest.cc

[ci-skip], no functionality changes

code management comments, 

---

googletest/test/googletest-output-test.py
googletest/test/gtest_test_utils.py

 formatting and small changes related to code management

---

googlemock/include/gmock/gmock-matchers.h
googletest/include/gtest/gtest-typed-test.h
googletest/test/googletest-output-test-golden-lin.txt
googletest/test/googletest-output-test_.cc
googletest/test/gtest-typed-test_test.cc

Googletest export

---

CMakeLists.txt
configure.ac

Use correct minor version for 1.8 branch

---

googlemock/docs/DesignDoc.md

[From](https://github.com/google/googletest/blob/master/googlemock/docs/DesignDoc.md#using-the-action-objects-type):
[To](https://github.com/svg153/googletest/blob/patch-1/googlemock/docs/DesignDoc.md#using-the-action-objects-type):

ACTION table format

---

library.json

Corrected the GitHub paths from 'abseil' to 'google'.

fix:  Correct GitHub paths

---

googletest/xcode/gtest.xcodeproj/project.pbxproj

Xcode project files contains some files which no longer exist. It makes build failure. This pull request removes them from Xcode project file.
Thanks for great product !!

Update Xcode project file

---

library.json

Added additional source and include directories.
This is still a work in progress.  It is difficult to test what the package manager does without committing changes and going round trip.  I do know that these are needed.

fix:  Correct library.json

---

googletest/docs/advanced.md

Repeat #2090

---

googletest/docs/primer.md

Avoid array index out of range

---

.gitignore
Makefile.am
googlemock/Makefile.am
googlemock/configure.ac
googletest/configure.ac

This wasn't entirely correctly configured...

Minor build system fixes.

---

googlemock/docs/DesignDoc.md

DesignDoc Markdown table was broken

---

googletest/docs/advanced.md

See https://github.com/google/googletest/issues/2065

Note about INSTANTIATE_TEST_SUITE_P / INSTANTIATE_TEST_CASE_P

---

googlemock/test/gmock-matchers_test.cc

Fixes https://github.com/google/googletest/issues/2284

Fixed issue #2284 (Incompatibility with C++17)

---

googletest/docs/primer.md

I noticed some small mistakes in primer.md. This PR fixes them.

Fix small errors in primer.md

---

.travis.yml

Remove trailing whitespaces

---

googlemock/README.md

Links to FAQ, Cheat Sheet, Cookbook, gMock for Dummies

Update README.md (issue #2352)

---

googletest/docs/advanced.md

This should fix some bad formatting on some Markdown tables...

Fix table formatting in advanced.md

---

googletest/docs/primer.md

This fixes a "what's left" of a table.

Fix an improperly generated table

---

googlemock/include/gmock/gmock-spec-builders.h
googlemock/include/gmock/internal/gmock-internal-utils.h
googlemock/test/gmock-internal-utils_test.cc
googlemock/test/gmock-matchers_test.cc
googletest/include/gtest/gtest-matchers.h
googletest/include/gtest/internal/gtest-internal.h
googletest/include/gtest/internal/gtest-port.h
googletest/test/googletest-output-test_.cc
googletest/test/gtest-typed-test_test.cc

Remove custom implementations of std::is_same

---

googlemock/include/gmock/gmock-matchers.h
googlemock/include/gmock/internal/gmock-internal-utils.h
googletest/include/gtest/internal/gtest-internal.h
googletest/test/gtest_unittest.cc

Remove a custom implementation of std::remove_const

---

googletest/include/gtest/internal/gtest-port.h
googletest/test/gtest_unittest.cc

Remove a custom implementation of std::add_lvalue_reference

---

CONTRIBUTING.md

Remove references to autotools and combine gTest & gMock sections

---

googlemock/docs/for_dummies.md
googletest/docs/advanced.md
googletest/docs/faq.md

Fix typo in documents

---

googletest/include/gtest/gtest-matchers.h
googletest/include/gtest/gtest-param-test.h
googletest/include/gtest/internal/gtest-internal.h
googletest/include/gtest/internal/gtest-port.h

This helps corrects builds with -Werror=suggest-overrides
Replaces #2473

Add many missing override keywords

---

googlemock/include/gmock/gmock-function-mocker.h
googlemock/test/gmock-function-mocker_test.cc

This reverts commit ba513d2c9525a7c986c115ed5d603f2cf17c6016, reversing
changes made to a3ca5b9e0bf9abc3bc639684966085c4d3182578.

Re-apply changes from #2498

---

googletest/include/gtest/internal/gtest-internal.h
googletest/test/gtest_unittest.cc

Added special catch for std::exception in GTEST_TEST_NO_THROW_

---

googletest/src/gtest.cc

Fixed warnings

---

googletest/test/googletest-output-test_.cc

Remove dead code in googletest-output-test

---

googletest/test/googletest-death-test-test.cc

Swap settimer and sigaction calls to avoid SIGPROF

---

googletest/include/gtest/internal/gtest-internal.h
googletest/test/gtest_unittest.cc

Enable protobuf printing for open-source proto messages.

---

googlemock/README.md

There is an unnecessary comma before 'and'

Removed a typo in README.md

---

README.md

Renamed related open source project name: Catch2 and Google Test Explorer -> C++ TestMate

README.dm: Renamed open source project 

---

googletest/src/gtest-typed-test.cc

Straight forward change, please review this patch.

Use count function instead of handwritten loop

---

googletest/include/gtest/internal/gtest-port.h

Fix build issue for MinGW

---

googletest/CMakeLists.txt
googletest/include/gtest/gtest-param-test.h
googletest/include/gtest/internal/gtest-param-util.h
googletest/test/gtest_list_output_unittest.py
googletest/test/gtest_list_output_unittest_.cc

Add correct line number to TEST_P test cases for gtest_output.

---

googletest/docs/faq.md

Found some typos while reading.
Thank you

Fixed some minor typos

---

googletest/include/gtest/internal/gtest-internal.h
googletest/include/gtest/internal/gtest-param-util.h
googletest/src/gtest-internal-inl.h
googletest/src/gtest.cc

Fix typos in comments

---

googletest/src/gtest.cc

Fix typo in CLI help message

---

googletest/README.md

Update cmake install doc according to #3094

Simplify cmake install file

---

README.md
docs/gmock_cheat_sheet.md
docs/gmock_for_dummies.md
docs/pkgconfig.md
docs/reference/actions.md
docs/reference/matchers.md
googletest/README.md

Fix typos in documents

---

CONTRIBUTING.md

I added an anchor tag in line number 39 and added a missing 'a' in line 72

Added an Anchor Tag in "see detail above"

---

docs/gmock_cook_book.md
googletest/test/gtest_pred_impl_unittest.cc
googletest/test/gtest_unittest.cc

https://pypi.org/project/codespell/

Fix typos discovered by codespell

---

BUILD.bazel

Fixes: 
Works around: https://github.com/bazelbuild/bazel/issues/12023
because I'm not sure how long it would take bazel to address it.

Fix linker errors on FreeBSD.

---

googlemock/src/gmock-spec-builders.cc

@cramertj, I like [your change](https://github.com/google/googletest/commit/1a3e2a265f35e604378156cd675b11ef0a184627) but let's improve it a bit. :)
~Everyone:
I'm not really sure if removal of that comma is correct (English is not my native language), but that's how I think it works. It would be nice if someone could review that.~

Fix a typo

---

googletest/src/gtest.cc

Fixes #3681
Signed-off-by: Ayush Joshi <ayush854032@gmail.com>

Allow to specify a random seed independently of whether shuffling is requested

---

googletest/README.md

CLA signed! Please, give me & others a bit more time to sign their CLA instead of closing the PR.

Let me give a change to try it again - updating to latest version

---

README.md

Removing commas.

---

googlemock/src/gmock-internal-utils.cc
googletest/src/gtest-printers.cc

Explicitly convert from int to char where error occurred
Closes #3915

Allow -Werror -Wconversion

---

docs/quickstart-bazel.md

Update link to Bazel installation guide

---

.github/workflows/gtest-ci.yml

https://github.com/actions/checkout/releases

Upgrade GitHub Actions Checkout

---

googletest/README.md

Signed-off-by: Ferenc Géczi <ferenc.gm@gmail.com>

Suggests a release with fixed CMakeLists.txt

---

WORKSPACE

Update Bazel build related dependencies

Update rules_python, bazel_skylib and platfroms

---

googletest/src/gtest.cc
googletest/test/googletest-color-test.py
googletest/test/gtest_unittest.cc

Fix [#3455](https://github.com/google/googletest/issues/3455)

Support kitty TERM

---

docs/gmock_cheat_sheet.md
docs/gmock_cook_book.md

https://github.com/google/googletest/issues/3067

Change MakeUnique -> std::make_unique in docs

---

googletest/README.md

Version 1.13.x and later require C++14.
Also fix missing closing backtick.

Change C++11 requirement to C++14

---

googletest/test/googletest-catch-exceptions-test.py

FITLER_OUT_SEH_TESTS_FLAG -> FILTER_OUT_SEH_TESTS_FLAG

Fix typo in googletest-catch-exceptions-test.py

---

googlemock/src/gmock_main.cc
googletest/include/gtest/internal/gtest-port-arch.h
googletest/include/gtest/internal/gtest-port.h
googletest/src/gtest-filepath.cc
googletest/src/gtest_main.cc

Added support for Nordic nRF52 series of MCUs

add support for nrf52

---

googletest/src/gtest-internal-inl.h

Use #if and not #ifdef to check filesystem support

---

docs/gmock_for_dummies.md
docs/primer.md
googlemock/README.md
googlemock/src/gmock-matchers.cc
googletest/README.md
googletest/cmake/internal_utils.cmake
googletest/include/gtest/internal/gtest-internal.h
googletest/include/gtest/internal/gtest-port.h
googletest/src/gtest-death-test.cc
googletest/src/gtest-internal-inl.h
googletest/src/gtest.cc

changed http to https

---

googletest/src/gtest.cc
googletest/test/googletest-color-test.py
googletest/test/gtest_unittest.cc

Add colored output support for Alacritty

---

googletest/src/gtest.cc
googletest/test/googletest-json-output-unittest.py
googletest/test/gtest_json_test_utils.py

Fix the gap between JSON and XML output.

Add skipped messages to JSON output (fixes #4507).
